### PR TITLE
Bug #149 filter grouping

### PR DESCRIPTION
**Pull request by jbudynk**
# Release Note

Fixes bug #149. If a dataset is filtered and then grouped with `group_counts(grpnum)`, the last bin in the grouped array, while less than `grpnum`, is included in the array. The sherpa documentation states that `group_counts(grpnum)` will group the dataset counts so that each bin contains at least `grpnum` counts.

This fix ensures that each bin in a grouped dataset upholds to the given user condition, be it enough counts, SNR, etc.

A number of simple grouping tests for each grouping method (`group_snr(), group_adapt(), etc.`) have also been added.
# Status

This bug is fixed in the sense that the steps in #149 result in the expected output. However, this fix only works for datasets that have been filtered before being grouped. We still need to discuss and fix what happens to unfilled bins in grouped datasets. 

Currently, if no filters have been applied to the dataset, the data is simply grouped by the external grplib functions, which by default leave the last unfilled bin in the grouped dataset. The unfilled groups are given a quality of 2; the user can ignore the unfilled group with `ignore_bad()`.

For now, I've put the PR on hold because one test, `sherpa/astro/tests/test_data.py::test_grouping::test_grouping_with_previous_quality_flags()`, will fail until we decide how to handle grouping, filtering, and quality flags. I can set this test to fail if we do not want to tackle this issue in this PR.

Note that a number of fitting tests are failing because the grouping logic has changed, which affects the fit results as the groups are different.
# Description

This bug is part of a bigger issue on grouping, filtering, and quality flags. We need to decide what the behavior of grouping should be when a bin is left unfilled - must it never be added to the grouped array in the external grplib code? Should sherpa handle ignoring unfilled bins internally? Should we make the user ignore the unfilled groups themselves? And so on.

### CODE REVIEW

**Comment by DougBurke** [comment]
@jbudynk - it looks like the tests are failing in multiple places, not just `sherpa/astro/tests/test_data.py::test_grouping::test_grouping_with_previous_quality_flags()` - is this expected with the current PR?

**Comment by jbudynk** [comment]
Yes - because the grouping is different, we expect some differences in the fit results for some tests. I haven't reconciled all of them because (1) I want to make sure I'm following the expected behavior of the tests, and (2) it's a little tedious and I need more time :) . 

Thanks for pointing this out - I'll add that to the status.

I mainly wanted to get this up so we have a place for discussing the grouping issues, and so it's easier to view the code changes.

**Comment by jbudynk** [comment]
Hmm... I am noticing more than just the statistics-related tests failing... all the tests in sherpa/astro/tests/test_data pass on my system (except test_grouping_with_previous_quality_flags(), which is expected to fail at this point), but I see them failing on Travis. I'll take a look...

**Comment by jbudynk** [comment]
Rebased. Original tip: 87077c2

**Comment by DougBurke** [comment]
@jbudynk - there still seems to be some unexpected failures arfter your rebase - e.g.

 - 1006.6 also fails in `test_ui.test_restore_usermodel` https://travis-ci.org/sherpa/sherpa/jobs/137350474#L4690

 - 1006.7 also fails with a problem loading in the io module https://travis-ci.org/sherpa/sherpa/jobs/137350475#L4553 - perhaps the test should be marked as `requires_fits` (although I'm not convinced that I understand what's actually gone on in this test failure, so I could be going doen the wrong rabbit hole)?

I suggest adding a "expected_to_fail" decorator (I forget how to do this) to `sherpa/astro/tests/test_data.py::test_grouping::test_grouping_with_previous_quality_flags` just so we know everything else is working with these patches. Then when we've resolved the test we can remove this hint to check everything is okay.

**Comment by olaurino** [comment]
> I suggest adding a "expected_to_fail" decorator (I forget how to do this) to sherpa/astro/tests/test_data.py::test_grouping::test_grouping_with_previous_quality_flags just so we know everything else is working with these patches. Then when we've resolved the test we can remove this hint to check everything is okay.

Since this test was added by this PR my counter-suggestion would be to remove it from this PR, and add it to a new branch backing a new PR, so we make sure we fix it, even though we decide it's not going to be fixed in the scope of this PR. I am not a fan of marking tests as expected to fail, even when the testing framework allows it.

**Comment by DougBurke** [comment]
I'll leave it up to @jbudynk which she prefers to do ;-)

**Comment by DougBurke** [comment]
@jbudynk it looks like there are still some issues with this PR, but not for all cases. Is it understood why this is happening, or do you need to look into it?

**Comment by jbudynk** [comment]
For the most part, yes. The fitting tests are most likely failing because the datasets were grouped beforehand. Since the groupings for those datasets may have changed, the fit results will change too. I still need to investigate what the right results should be...

I've added a fix for the `test_ui.restore_usermodel()` failure in the latest commit. I was catching the wrong type of exception elsewhere in the code.

I've also removed the quality flags test since this issue can be tackled in another PR. Right now, we're just trying to make sure the last unfilled bin in the array is not included in the grouped view of the dataset. If it turns out that we'll need that test, we can add it back in.

**Comment by DougBurke** [comment]
I don't quite understand the pattern of failures - e.g. why does run#2 with XSPEC pass but runs #4 and #5 with XSPEC fail? Is it something like run#2 doesn't load in the sherpa-test-data repository so the tests aren't run in that build, or is it something else?

**Comment by DougBurke** [comment]
Run #7 also looks to be a completely different failure (hence the separate comment) - e.g. https://travis-ci.org/sherpa/sherpa/jobs/137564449#L4542 - fails with

    ImportError: Cannot import selected FITS I/O backend pyfits_backend.

**Comment by jbudynk** [comment]
Huh... yeah not sure what's happening there. I was focusing on the fit results failures. I haven't looked at these other failures yet to be honest. But I'll take a look at them.

**Comment by jbudynk** [comment]
I'm adding the quality flag test back in... it's probably best to tackle both issues at once so we don't have to possibly rewrite grouping and/or fit results tests twice.

**Comment by DougBurke** [comment]
@olaurino is the build failure for the setuptools test (run 1) the same issue that you mentioned on email; that is, it is time to remove this particular build from the test suite?

https://travis-ci.org/sherpa/sherpa/jobs/138910868#L410

i.e. cherry-pick your commit 43df53d

**Comment by olaurino** [comment]
> is the build failure for the setuptools test (run 1) the same issue that you mentioned on email; that is, it is time to remove this particular build from the test suite?

Yes, that's correct, @DougBurke.

**Comment by jbudynk** [comment]
Hmm... I notice an issue with the current fix. Right now, the last bin in a grouped dataset is *always* removed if the dataset was filtered. For unfilled bins, this is an OK fix, but if the group condition is satisfied in the last bin, we don't want to remove that last bin from the grouped view. This is the fix introduced in 5f20972f7f2f, in `sherpa/data.py`.

You can see an issue with `sherpa/astro/tests/test_astro.py::test_threads::test_xmm()`. The dataset is grouped with `group_width(10)`, and the notice range is channel 40 to 201. The last bin, while is contains 10 channels and has a good quality flag, is removed from the filtered view. That should not happen.

Unfortunately, I hadn't covered this issue in the tests because only one of the tests filters the dataset before grouping, and that is for Nick Lee's bug report with quality flags (the one just added back in today). I'll add a test that sets broad filter on one of the simple grouping tests so we can catch this issue.

**Comment by DougBurke** [comment]
Once we've resolved this issue I'd like to make sure that at least one test case is added to the `sherpa.astro.ui.save_all` test suite - i.e. `sherpa/astro/ui/tests/test_serialize.py` - to make sure that the correct filter and quality flags are saved. This can be done in a separate PR, but I wanted to write it down somewhere so that I don't forget to do it.

**Comment by jbudynk** [comment]
Rebasing on master, with new commits. Original tip was 3203cd5.

**Comment by jbudynk** [comment]
I've got a fix for the issue of making sure each grouping condition is met, and there are no "bad quality" groups shown when viewing the "grouped" view of a dataset (e.g., using `sherpa.astro.ui.get_data().get_dep(filter=True)`). 

However, there is a change I don't like and would like some feedback on and more testing to see if this breaks any other behavior.

I made a new function, `_ignore_bad_groups()`, which works similarly to `ignore_bad()`, but doesn't undo the previously-set filters. It only ignores channels with quality == 2.

To understand the changes better, I'll summarize how grplib's code comes into play. When a dataset is grouped, and a specific group doesn't meet the grouping criteria, the channels in that group are assigned a value of 2. This quality array is assigned to `self.quality` in DataPHA. So in `sherpa.astro.data::DataPHA._dynamic_group()`,  `_ignore_bad_groups()` is called, which sets `self.quality_filter`, a boolean array representation of `self.quality`. This boolean array is used to further filter the groups in `DataPHA.apply_grouping()`:

Originally, I thought we could change the grouping array that comes out of grplib, so that when we found group qualities of 2, we would set the `self.grouping` in those bins to 0, which in grplib's terms means "unused group". However, back when Stephen was working here, "0" groups were considered groups themselves (for filtering reasons?? I guess in case there is a big "ignore" region in the middle of a dataset, and you group the dataset, that you can see that big gap in the data). The relevant code is in [sherpa/include/sherpa/astro/utils.hh::_do_group()](https://github.com/sherpa/sherpa/blob/master/sherpa/include/sherpa/astro/utils.hh#L355) by line [374](https://github.com/sherpa/sherpa/blob/master/sherpa/include/sherpa/astro/utils.hh#L374). All group values >= 0 are considered "groups", and all other values are considered to be inside a group.

**Comment by jbudynk** [comment]
Tests `sherpa/astro/ui/tests/test_serialize.py::test_ui::test_canonical_pha_grouped`, `sherpa/astro/ui/tests/test_serialize.py::test_ui::test_canonical_pha_back`, and `sherpa/astro/tests/test_astro.py::test_threads::test_setfullmodel` are erroring due to a VisibleDeprecationWarning in [DataPHA.get_noticed_channels()](https://github.com/sherpa/sherpa/blob/bug-%23149-filter-grouping/sherpa/astro/data.py#L1580). [DataPHA.get_mask()](https://github.com/sherpa/sherpa/blob/bug-%23149-filter-grouping/sherpa/astro/data.py#L1582) returns an array of different dimensions than the PHA channels.

**Comment by DougBurke** [comment]
The deprecation warnings are part of issue #273 (or, at least, they now are; the original 273 report doesn't explicitly list this example).

**Comment by jbudynk** [comment]
On a note related to grouping but not to this issue:

in [DataPHA._dynamic_group()](https://github.com/sherpa/sherpa/blob/master/sherpa/astro/data.py#L856), the following is stated: 

        self.grouping, self.quality = group_func(*args, **kwargs)
        self.group()
        self._original_groups = False

        if do_notice:
            # self.group() above has cleared the filter if applicable
            # No, that just sets a flag.  So manually clear filter
            # here
            self.ignore()
            for vals in parse_expr(old_filter):
                self.notice(*vals)

self.group() *does* clear the filter, if applicable. It calls [`_set_grouped()`](https://github.com/sherpa/sherpa/blob/master/sherpa/astro/data.py#L253), which does the whole `self.ignore(); for vals in parse_expr(old_filter):` called in _dynamic_group(). The `if do_notice:` conditional can be removed.

**Comment by olaurino** [comment]
The warnings here are different, so this is NOT related to #273 (which btw should be fixed in the context of a different bug fix by a PR I am about to issue).

**Comment by olaurino** [comment]
This PR is no longer relevant, so while it might still contain code and/or tests that will be useful in the future, I am going to close it.

**Pull request closed without merging**
