### PR TITLE
Support overplot option in plot_fit_xxx (issue #700)

### LINKED ISSUE #700: (overplot=True) with double plots
The option `overplot=True` in the plots which generate one display window allow to overplot different data sets in the same plot window. For example 

      plot_data(1) 
      plot_data(2,overplot=True)

will generate a plot showing two data sets in the same plot. However,
`overplot=True` is  not generating the plots for two data sets in the case of double plots.
For example

    plot_fit_resid(1)
    plot_fit_resid(2,overplot=True)'

will plot the first data set, but then regenerate the second plot after deleting the first one.
There is no Error mgs, so in theory this is allowed, but the current behaviour is consistent with the
4.11 and older versions of Sherpa.

### PR DESCRIPTION
**Pull request by DougBurke**
# Summary

The overplot argument can now be used with the plot_fit_xxx and plot_bkg_fit_xxx routines (e.g. plot_fit_ratio).

Fix #700 

# Details

This allows you to say

    plot_fit_resid(ylog=True)
    plot_fit_resid(2, overplot=True)

The underlying plot objects are poorly documented, so it's not obvious what they were meant to be doing. I have taken the liberty to change things around a little bit to support the overplot setting. Tests have been added to show this is working, and fortunately it's the only use case for JointPlot in the ui code.

The tests trigger #571 so I've added a suppressor to the test code. I  would prefer this to be local to the test, rather than for the whole test suite, but that is a larger change.

### CODE REVIEW

**Comment by DougBurke** [comment]
@anetasie - does this work like you'd want for #700 ?

**Review by anetasie — APPROVED** [review]

**Comment by anetasie** [comment]
@DougBurke Yes, it looks good and it does what I wanted for #700. Thanks!

**Comment by anetasie** [comment]
@wmclaugh We want this for 4.12.2

**Comment by DougBurke** [comment]
Rebased because of #906 being merged

**Comment by DougBurke** [comment]
I've added the fix from #955 to get the tests to pass.

**Comment by DougBurke** [comment]
Rebased now #955 has been merged

**Review by dtnguyen2 — APPROVED** [review]

**Comment by wmclaugh** [comment]
@DougBurke - Can you please rebase so this can get merged.

**Comment by DougBurke** [comment]
@wmclaugh - well, that was a surprisingly more-involved rebase than I expected. It definitely needs to pass travis before merging :-)

**Comment by DougBurke** [comment]
**ARGH** stupid rebases

**Comment by DougBurke** [comment]
So, I don't know if that was something that got lost in the rebase or is because of other changes that have been recently merged. It looks like we needed to add a separate warning check for a Matlpotlib 2 warning compared to Matplotlib 3.

**Comment by DougBurke** [comment]
@wmclaugh - the tests now pass. It's marked as failed because the coverage has changed for the worse. However, if you look this is one of those odd cases, as the coverage has decreased in files that haven't been touched in this PR and are not related to the tests I've added.

**Pull request merged**
