### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by olaurino**
This PR updates the README to account for the new python 3 support and the updated release number.

### CODE REVIEW

**Comment by anetasie** [comment]
I'm done with the editing.

**Comment by olaurino** [comment]
Is everybody happy with these changes? Can I merge them in the release branch? @wmclaugh @anetasie @DougBurke

**Comment by DougBurke** [comment]
I am not going to be able to review them today, but that shouldn't stop them being merged

**Comment by anetasie** [comment]
I just checked and the changes look ok

**Pull request merged**
