### PR TITLE
CI: pip submodule test to report coverage

### PR DESCRIPTION
**Pull request by DougBurke**
# Summary

Report the coverage data from the pip CI run. This only changes the GitHub Actions runs.

# Details

Let's report the coverage data. I don't expect it to catch anything "new" (i.e. not in other runs from the conda CI), but we may as well collect the data as we create it.

### CODE REVIEW

**Comment by DougBurke** [comment]
Hmm, it looks like we don't actually have any `submodule` tests with pip. Should this section be removed from the GH Action, or do we want one?

**Comment by DougBurke** [comment]
Actually, I see that the YML has a typo in it:

https://github.com/sherpa/sherpa/blob/1b7f59028ff8d377744aaa8dfd0330909c59df48/.github/workflows/ci-pip-workflow.yml#L75

should say `submodule` not `submoule`. We don't have any tests that trigger this section though.

@Marie-Terrell - what was the intention with the pip "submodule" test?

**Comment by Marie-Terrell** [comment]
Woops. Good point. In the translation, I combined the information from the travis/test.sh (to pick up the "submodule" section) and the test matrix from Travis. I had noted the comment in the Travis test matrix:
`    # A relatively basic installation - NumPy and AstroPy - with no test data; this is similar to the preceeding
    # test, so perhaps could be combined?
`
And combined the two. Which in turn removed any "submodule" tests for the pip side of things causing me to not catch that error. I see no issue adding that test back in (with the spelling mistake fixed).

**Comment by Marie-Terrell** [comment]
I'm sorry. Hit the wrong button.

**Comment by DougBurke** [comment]
You could push the fix to this branch or start a new one. Would the idea be a basic test (so no astropy/matplotlib) or to have astropy at least (as most of the data files require support for an  I/O library)?

**Comment by Marie-Terrell** [comment]
Hopefully, that works. The two final tests previously were fairly minimal with just astropy. The only difference was the data (none vs submodule). So, this new addition should cover that.

**Comment by DougBurke** [comment]
So, I don't understand the coverage info here

- 4ae9e0e (my last one) has https://codecov.io/gh/sherpa/sherpa/commit/4ae9e0ef53c1956a61cf87caad88d6c93c05e1a2/build
- 4e91f16 (Marie's) has https://codecov.io/gh/sherpa/sherpa/commit/4e91f161b094d38b908a4063314941598b8199d3/build

Mine has 8 builds contributing (four labelled 469912213 and four labelled  470020430), and that in itself is odd as we only have 7 conda builds.

Marie's only has 5 builds contributing (one labelled 470262490 and four 470262491), which is presumably why the codecov coverage appears to be lower.

Actually, probably not: if you look at one of the 4 builds from mine they are all the same, so we really have two, which are

- https://github.com/sherpa/sherpa/actions/runs/469912213 labelled me opening #1049
- https://github.com/sherpa/sherpa/actions/runs/470020430 labelled Marie re-opening #1049

and Marie's two are

- https://github.com/sherpa/sherpa/actions/runs/470262490 labelled synchronize #1049 for pip CI build
- https://github.com/sherpa/sherpa/actions/runs/470262491 labelled synchronize #1049 for conda CI build

So I think that makes more sense (presumably you multiple reports until all the CI builds for a particular workflow complete, and we only have one pip build contributing). For my build there were two separate runs thanks to the PR being closed/re-opened.

It still doesn't explain why the coverage appears to go down though.

**Comment by DougBurke** [comment]
Aha, here's an interesting page:

https://codecov.io/gh/sherpa/sherpa/pull/1049/tree

which shows that the pip install has triggered coverage of files in [`work/sherpa/sherpa/sherpa`](https://codecov.io/gh/sherpa/sherpa/pull/1049/tree/work/sherpa/sherpa/sherpa) (a whole lotta sherpa) and the existing coverage is for [`sherpa`[(https://codecov.io/gh/sherpa/sherpa/pull/1049/tree/sherpa)

So there's something "odd" about the coverage report in the pip build compared to the conda build.

**Comment by DougBurke** [comment]
So now https://codecov.io/gh/sherpa/sherpa/pull/1049/tree looks more sensible (only one directory). I don't know how `pytest` was picking up the actual tests to run from the `$HOME` directory but I think I'll just ignore this...

**Review by Marie-Terrell — APPROVED** [review]
Looks good to me!

**Pull request merged**
