### PR TITLE
pep8/pyflakes changes to sherpa.instrument

### PR DESCRIPTION
**Pull request by DougBurke**
There is no functional change to the code. Changes include:

  - explicit import lists (removal of `from ... import *`)
  - addition/removal of blank space(s) between characters on a line
  - addition/removal of blank lines

I noticed this when working on the Sphinx documentation, and wanted to fix the code so that any future changes can be made from a slightly-cleaner base.

### CODE REVIEW

**Comment by DougBurke** [comment]
I resisted the temptation to look into the different string-handling checks (some use `six.string_types` and some, later on, use `str` and `numpy.string_`), as we don't have tests of these parts of the code. I wanted this to be an easy review!

**Comment by olaurino** [comment]
Rebasing to get newest update and make CI run, since this PR has been open for a while. Was 104fc12.

**Comment by DougBurke** [comment]
@olaurino is there any reason why this hasn't been merged yet?

**Comment by olaurino** [comment]
I couldn't merge it before I left and I didn't find time to merge it yet. Maybe it should be rebased to make sure the tests run again against the latest changes to master, though.

**Comment by DougBurke** [comment]
I am pretty sure that there have been no changes to master since the last rebase you did.

**Pull request merged**
