### PR TITLE
Remove unused opt

### PR DESCRIPTION
**Pull request by DougBurke**
During writing this I've found an actual bug in the existing code, but it is obviously not triggered in normal use - am investigating

# Summary

The development code from the sherpa.optmethods.* modules has been moved out to the scripts/opt/ directory.

# Details

The `ncoresde`, `ncoresnm`, and `opt` modules in `sherpa.optmethods` all contained code that could only be evaluated by executing the module directly. This code is not used by Sherpa - either in normal use or even during tests - but was intended for development. This has been moved out to the `scripts/opt/` directory, so it is available if anyone wants to look at this, but is not part of the Sherpa code base used by users. An alternative would be to just remove this code with a note that it can be got from git history, but that is hard to identify.

See #995 for more discussion.

I've also applied a modicum of code cleanup, to remove some C++-isms.

### CODE REVIEW

**Comment by DougBurke** [comment]
So the two things for @dtnguyen2 to comment on based on this are

1. https://github.com/sherpa/sherpa/issues/995#issuecomment-1012229826 - my guess is that support for `numcores>1` can be removed from `montecarlo`, which would then mean a lot of code could be removed, or maybe I'm mis-reading the code
2. The `SimplexBase.check_convergence` method in `sherpa.optmethods.opt` includes code that can't be reached - in this PR it's labelled by `# NOTE: this code is never used` - is this code that can get removed or is there an issue in `check_convergence`?

**Comment by dtnguyen2** [comment]
I will have to take a closer look, but
```Python
def montecarlo(fcn, x0, xmin, xmax, ftol=EPSILON, maxfev=None, verbose=0,
               seed=74815, population_size=None, xprob=0.9,
               weighting_factor=0.8, numcores=1):
```
does have an option with ```numcores``` so the multiprocessor version of ```montecarlo``` was written in Python cause it was much easier to call Python multiprocessing module from Python than from C++ land.

**Comment by harlantc** [comment]
If this code is never used, we could add it to the ignored files for codecov, as I see it did cause a coverage change.

**Comment by dtnguyen2** [comment]
```self.polytope```  as defined in the _ncoresde.py_ is a ```SimplexRandom```
devel12-115: awk 'NR >= 298 && NR <= 299' < ncoresde.py 
```Python
        self.polytope = \
            SimplexRandom(func, npop, xpar, xmin, xmax, step, seed, factor)
```
which inherits from ```SimplexBase```
devel12-119: awk 'NR == 301' < opt.py
```Python
class SimplexRandom(SimplexBase):
```
so yes some of the code in ```SimplexBase.check_convergence``` does get call since it is called with ```method == 0```; However, if  ```method ==2``` then all the code within ```SimplexBase.check_convergence```  will be used.  Who knows someday someone may want to change it.
devel12-125: awk 'NR >= 383 && NR <= 385' < ncoresde.py
```
            self.polytope.sort()
            if self.polytope.check_convergence(tol, 0):
                break
```

As a sanity check, I changed ```SimplexBase.check_convergence``` to always return ```True```
(testing-PR) [dtn@devel12 optmethods]$ git diff
```bash
diff --git a/sherpa/optmethods/opt.py b/sherpa/optmethods/opt.py
index aed93920..4edd6070 100755
--- a/sherpa/optmethods/opt.py
+++ b/sherpa/optmethods/opt.py
@@ -191,6 +191,7 @@ class SimplexBase:
             return max_xi_x0 <= tolerance * max(1.0, np.dot(x0, x0))
 
         if 0 == method:
+            return True
             if is_max_length_small_enough(ftol):
                 return True
         elif 2 == method:
```
to confirm that the method does get called:

(testing-PR) [dtn@devel12 sherpa]$ pytest sherpa/optmethods/tests/test_ncoresopt.py 

```bash
================================= test session starts ==================================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /export/sherpa, configfile: pytest.ini
collected 41 items                                                                     

sherpa/optmethods/tests/test_ncoresopt.py .F......ss....ss..ssss..ssss....s.s.s. [ 92%]
F..                                                                              [100%]

======================================= FAILURES =======================================
__________________________________ test_Ackley[opt1] ___________________________________

opt = <sherpa.optmethods.ncoresde.ncoresDifEvo object at 0x7fe32a791550>, npar = 4

    @pytest.mark.parametrize("opt", [NCORES_NM, NCORES_DE])
    def test_Ackley(opt, npar=4):
>       tst_opt(opt, _tstoptfct.Ackley, npar)

sherpa/optmethods/tests/test_ncoresopt.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

opt = <sherpa.optmethods.ncoresde.ncoresDifEvo object at 0x7fe32a791550>
fcn = <built-in function Ackley>, npar = 4, reltol = 0.001, abstol = 0.001

    def tst_opt(opt, fcn, npar, reltol=1.0e-3, abstol=1.0e-3):
        def func(arg):
            return fcn(arg)[0]
        x0, xmin, xmax, fmin = init(fcn.__name__, npar)
        nfev, fval, par = opt(func, x0, xmin, xmax)
>       assert fmin == pytest.approx(fval, rel=reltol, abs=abstol)
E       assert 0.0 == 6.509685842281442 ± 6.5e-03
E        +  where 6.509685842281442 ± 6.5e-03 = <function approx at 0x7fe34b491790>(6.509685842281442, rel=0.001, abs=0.001)
E        +    where <function approx at 0x7fe34b491790> = pytest.approx

sherpa/optmethods/tests/test_ncoresopt.py:40: AssertionError
__________________________________ test_Shubert[opt1] __________________________________

opt = <sherpa.optmethods.ncoresde.ncoresDifEvo object at 0x7fe32a791550>, npar = 2

    @pytest.mark.parametrize("opt", [NCORES_NM, NCORES_DE])
    def test_Shubert(opt, npar=2):
>       tst_opt(opt, _tstoptfct.Shubert, npar)

sherpa/optmethods/tests/test_ncoresopt.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

opt = <sherpa.optmethods.ncoresde.ncoresDifEvo object at 0x7fe32a791550>
fcn = <built-in function Shubert>, npar = 2, reltol = 0.001, abstol = 0.001

    def tst_opt(opt, fcn, npar, reltol=1.0e-3, abstol=1.0e-3):
        def func(arg):
            return fcn(arg)[0]
        x0, xmin, xmax, fmin = init(fcn.__name__, npar)
        nfev, fval, par = opt(func, x0, xmin, xmax)
>       assert fmin == pytest.approx(fval, rel=reltol, abs=abstol)
E       assert -24.06 == -16.943104753207905 ± 1.7e-02
E        +  where -16.943104753207905 ± 1.7e-02 = <function approx at 0x7fe34b491790>(-16.943104753207905, rel=0.001, abs=0.001)
E        +    where <function approx at 0x7fe34b491790> = pytest.approx

sherpa/optmethods/tests/test_ncoresopt.py:40: AssertionError
=============================== short test summary info ================================
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:63: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:79: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:90: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:96: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:107: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:113: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:133: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:142: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:151: need --runslow option to run
======================= 2 failed, 24 passed, 15 skipped in 1.83s =======================
```

**Comment by DougBurke** [comment]
I'm closing this as several wires were crossed.

**Pull request closed without merging**
