### PR TITLE
Pytest opt

### PR DESCRIPTION
**Pull request by dtnguyen2**
This PR converts the optimization tests from SherpaTest to pytest; Moreover, additional tests were added in preparation for some upcoming infrastructure changes.  The new combine tests now takes 21 secs for 207 tests vs 40 secs for 44 tests.   BTW, only the test code were changed so the user should not notice any changes.

### CODE REVIEW

**Comment by dtnguyen2** [comment]
The default tests used to take 3.29 secs for 27 tests and 36.38  secs for 17 tests for the default and ncores optimization tests, respectively:

```
(sherpa) [dtn@devel12 sherpa]$ pytest sherpa/optmethods/tests/test_optmethods.py 
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /export/sherpa, inifile: pytest.ini
plugins: arraydiff-0.3, xdist-1.29.0, forked-1.0.2, openfiles-0.3.2, doctestplus-0.3.0, remotedata-0.3.1
collected 27 items                                                             

sherpa/optmethods/tests/test_optmethods.py ...........................   [100%]

========================== 27 passed in 3.29 seconds ===========================

(sherpa) [dtn@devel12 sherpa]$ pytest sherpa/optmethods/tests/test_ncoresopt.py  
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /export/sherpa, inifile: pytest.ini
plugins: arraydiff-0.3, xdist-1.29.0, forked-1.0.2, openfiles-0.3.2, doctestplus-0.3.0, remotedata-0.3.1
collected 21 items                                                             

sherpa/optmethods/tests/test_ncoresopt.py .................ssss          [100%]

=========================== short test summary info ============================
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:249: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:261: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:273: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:285: need --runslow option to run
==================== 17 passed, 4 skipped in 36.38 seconds =====================

```
but the new tests now takes 14 secs for 184 tests and 6.94 secs for 23 tests for the default and ncores optimization tests, respectively. The combine tests now takes 21 secs for 207 tests vs 40 secs for 44 tests.

```
(sherpa) [dtn@devel12 sherpa]$ pytest sherpa/optmethods/tests/test_optmethods.py 
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /export/sherpa, inifile: pytest.ini
plugins: arraydiff-0.3, xdist-1.29.0, forked-1.0.2, openfiles-0.3.2, doctestplus-0.3.0, remotedata-0.3.1
collected 236 items                                                            

sherpa/optmethods/tests/test_optmethods.py ....xxxxx.................... [ 12%]
.......xx..ssss........x.......ssss.........x.......x.xssss....x........ [ 42%]
...xxxx................................x.x...............x...........x.. [ 73%]
x.xx.xx.xx................xx.x......x..x.x...x.xx.xx.x...x.....          [100%]

=========================== short test summary info ============================
SKIPPED [4] sherpa/optmethods/tests/test_optmethods.py:98: need --runslow option to run
SKIPPED [4] sherpa/optmethods/tests/test_optmethods.py:120: need --runslow option to run
SKIPPED [4] sherpa/optmethods/tests/test_optmethods.py:150: need --runslow option to run
============= 184 passed, 12 skipped, 40 xfailed in 14.00 seconds ==============

(sherpa) [dtn@devel12 sherpa]$ pytest sherpa/optmethods/tests/test_ncoresopt.py  
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /export/sherpa, inifile: pytest.ini
plugins: arraydiff-0.3, xdist-1.29.0, forked-1.0.2, openfiles-0.3.2, doctestplus-0.3.0, remotedata-0.3.1
collected 38 items                                                             

sherpa/optmethods/tests/test_ncoresopt.py ........ss....ss..ssss..ssss.. [ 78%]
.sss....                                                                 [100%]

=========================== short test summary info ============================
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:57: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:70: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:79: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:84: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:93: need --runslow option to run
SKIPPED [2] sherpa/optmethods/tests/test_ncoresopt.py:98: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:115: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:123: need --runslow option to run
SKIPPED [1] sherpa/optmethods/tests/test_ncoresopt.py:131: need --runslow option to run
==================== 23 passed, 15 skipped in 6.94 seconds =====================
```

running the tests with the ```--runslow``` option takes a lot longer but the number of tests increases from 207 to 238. 

```
(sherpa) [dtn@devel12 sherpa]$ pytest --runslow sherpa/optmethods/tests/test_optmethods.py 
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /export/sherpa, inifile: pytest.ini
plugins: arraydiff-0.3, xdist-1.29.0, forked-1.0.2, openfiles-0.3.2, doctestplus-0.3.0, remotedata-0.3.1
collected 236 items                                                            

sherpa/optmethods/tests/test_optmethods.py ....xxxxx.................... [ 12%]
.......xx..............x....................x.......x.x........x........ [ 42%]
...xxxx................................x.x...............x...........x.. [ 73%]
x.xx.xx.xx................xx.x......x..x.x...x.xx.xx.x...x.....          [100%]

=================== 196 passed, 40 xfailed in 25.72 seconds ====================

(sherpa) [dtn@devel12 sherpa]$ pytest --runslow sherpa/optmethods/tests/test_ncoresopt.py 
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /export/sherpa, inifile: pytest.ini
plugins: arraydiff-0.3, xdist-1.29.0, forked-1.0.2, openfiles-0.3.2, doctestplus-0.3.0, remotedata-0.3.1
collected 38 items                                                             

sherpa/optmethods/tests/test_ncoresopt.py .............................. [ 78%]
........                                                                 [100%]

========================= 38 passed in 155.78 seconds ==========================

```

**Comment by DougBurke** [comment]
@dtnguyen2 - thanks for this.

**Comment by DougBurke** [comment]
@dtnguyen2 - can the draft label be removed from this now?

**Comment by DougBurke** [comment]
@dtnguyen2 - I've just run using the master branch with #810 merged in, and it claims that one of your new tests has passed even though marked XFAIL. If you run with `python setup.py test -a -rX` theh  I you should see it (or just `pytest -rX`). The `sherpa/astro/xspec` test is understand, it's the `test_penaltyII[lmdif]` case that is now marked as an unexpected pass.

```
================================== short test summary info ===================================
XPASS sherpa/astro/xspec/tests/test_xspec_unit.py::test_chatter_default
XPASS sherpa/optmethods/tests/test_optmethods.py::test_penaltyII[lmdif]
============ 2792 passed, 353 skipped, 62 xfailed, 2 xpassed in 64.05s (0:01:04) =============
```

Should the XPASS here for `test_penaltyII` be removed, or left in?

**Comment by DougBurke** [comment]
Hmm, with a few runs with Python 3.7 I don't see it. I can't guarantee it's python 3.8 only, but I've added a note to #730 about it just in case.

**Pull request merged**
