### PR TITLE
default to astropy.io.fits instead of pyfits

### PR DESCRIPTION
**Pull request by olaurino**
Sherpa tries to import `astropy.io.fits` when the backend configuration is set to `pyfits`. If `astropy` is not present, Sherpa tries to fall back to using `pyfits`, if available.

This PR is largely based on #6, but it has been rebased to depend on #10 (now #28) instead of the other way around.

Since this PR is based off #28, when #28 is merged this PR will result in a single commit introducing `astropy`, a simple test, and an updated `has_fits_support` check.

### CODE REVIEW

**Comment by DougBurke** [comment]
I'm pretty sure I've seen this recently (today or yesterday) elsewhere, but I forget. I see a `RuntimeWarning` from one of the tests:

```
% sherpa_test
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
Failed importing sherpa.astro.xspec: No module named _xspec
  Found 7/7 tests for sherpa.astro.tests.test_datastack
  Found 1/1 tests for sherpa.astro.models.tests.test_models
  Found 25/25 tests for sherpa.astro.tests.test_optical
  Found 2/2 tests for sherpa.astro.sim.tests.test_sim
  Found 26/26 tests for sherpa.astro.tests.test_astro
  Found 6/6 tests for sherpa.astro.tests.test_data
  Found 1/1 tests for sherpa.astro.tests.test_plot
  Found 16/16 tests for sherpa.astro.tests.test_ui
  Found 1/1 tests for sherpa.astro.tests.test_nan
  Found 1/1 tests for sherpa.astro.utils.tests.test_utils
  Found 4/4 tests for sherpa.estmethods.tests.test_estmethods
  Found 6/6 tests for sherpa.image.tests.test_image
  Found 6/6 tests for sherpa.models.tests.test_template
  Found 12/12 tests for sherpa.models.tests.test_parameter
  Found 14/14 tests for sherpa.models.tests.test_model
  Found 1/1 tests for sherpa.models.tests.test_basic
  Found 26/26 tests for sherpa.optmethods.tests.test_optmethods
  Found 18/18 tests for sherpa.plot.tests.test_plot
  Found 18/18 tests for sherpa.sim.tests.test_sim
  Found 1/1 tests for sherpa.tests.test_stack
  Found 5/5 tests for sherpa.tests.test_sherpa
  Found 8/8 tests for sherpa.tests.test_ui
  Found 1/1 tests for sherpa.utils.tests.test_err
  Found 43/43 tests for sherpa.utils.tests.test_root
  Found 10/10 tests for sherpa.utils.tests.test_utils
  Found 1/1 tests for sherpa.utils.tests.test_integration
.................................ssssssssssssssssssssssssssss.......sss..ssssssssssss./home/naridge/data/my-sherpa/sherpa-omar/sherpa/estmethods/__init__.py:369: RuntimeWarning: invalid value encountered in sqrt
  diag = (sigma * numpy.sqrt(inv_info)).diagonal()
....sssssssssss..........................................................ssssss...........................sssss.sssssss.......................................................
----------------------------------------------------------------------
Ran 260 tests in 27.494s

OK (skipped=72)
```

It's repeatable, but I don't understand why I don't see it in other test runs (e.g. for PR #28).

**Comment by DougBurke** [comment]
Can we run `autopep8` on these files, just to start things off? I went through and ran

```
% autopep8 --select E101,W191 --in-place foo.py
````

for a number of files changed in this patch set and the results look easy to review for most files, so saving time when we flip the pep8 indentation switch later. These are changes to the tests themselves, so would not be checked by the new testing infrastructure we are waiting for to ensure there's no changes when `autopep8` is run on the main code base.

Note that `sherpa/astro/ui/tests/test_ui.py` has what appears to be the largest number of changes; from my review they look okay. After these changes `sherpa_test` still runs.

**Comment by DougBurke** [comment]
Note that the warning message from the test comes from (found by running `sherpa_test -v 3`)

```
test_covar (sherpa.estmethods.tests.test_estmethods.test_estmethods)/home/naridge/data/my-sherpa/sherpa-omar/sherpa/estmethods/__init__.py:369: RuntimeWarning: invalid value encountered in sqrt
  diag = (sigma * numpy.sqrt(inv_info)).diagonal()
 ... ok
```

**Comment by olaurino** [comment]
@DougBurke this may most likely be related to the numpy version, and since astropy pulls a more recent numpy version in conda (unless you pinned it), this seems to be consistent with your report. Could you try to manually downgrade numpy to 1.8.2 and see if the warning is still there?

**Comment by DougBurke** [comment]
@olaurino this was with a downgraded NumPy, as shown below, but I'll try a clean re-install with 1.8 just to check.

```
% conda list numpy
# packages in environment at /home/naridge/local/anaconda/envs/sherpa-omar:
#
You are using pip version 6.1.1, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
numpy                     1.8.2                    py27_0  
```

**Comment by DougBurke** [comment]
Aha, when I have a "clean" installation, with just version 1.8.2 of numpy (e.g. with just `conda create -n foo python=2.7 matplotlib pyfits`) I don't see the warning. If I install `astropy` instead, and then downgrade `numpy` by installing `pyfits` later, it seems that I do see the warning.

**Comment by DougBurke** [comment]
Not sure the numpy warning is entirely down to version differences in numpy, since I get the warning in both 1.8.1 and 1.9.

```
% python
Python 2.7.6 (default, Apr 18 2014, 17:48:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.8.1'
>>> np.sqrt([1,2,3])
array([ 1.        ,  1.41421356,  1.73205081])
>>> np.sqrt([1,-2,3])
__main__:1: RuntimeWarning: invalid value encountered in sqrt
array([ 1.        ,         nan,  1.73205081])
>>> np.sqrt([1,-2,3])
array([ 1.        ,         nan,  1.73205081])
```

and

```
% python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Apr 14 2015, 12:54:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import numpy as np
>>> np.version.version
'1.9.2'
>>> np.sqrt([1,2,3])
array([ 1.        ,  1.41421356,  1.73205081])
>>> np.sqrt([1,-2,3])
__main__:1: RuntimeWarning: invalid value encountered in sqrt
array([ 1.        ,         nan,  1.73205081])
>>> np.sqrt([1,-2,3])
array([ 1.        ,         nan,  1.73205081])
>>> 
```

There's nothing obvious to me in `test_estmethods.py` that turns on/off warnings. Anyway, I think that this is a digression from this PR, and should be treated separately; @olaurino if you agree I'll open a new ticket.

**Comment by olaurino** [comment]
Agreed. Thanks!

**Comment by DougBurke** [comment]
I was just about to label this pr:merge but saw that there's merge conflicts.

**Comment by DougBurke** [comment]
I've labelled this pr:merge for once the merge conflicts have been resolved.

**Comment by olaurino** [comment]
@DougBurke apparently there are no conflicts: it may be that GitHub does not use the recursive strategy to test the merges under the hood. As a matter of fact, if I try to use the resolve strategy from the command line, I get some easy-to-fix conflicts.

I am going to rebase this branch for two reasons: a) it makes the history cleaner and easier to follow and b) it is a good test case for documenting rebasing in git.

I don't see any reasons to create a new PR, though, as the discussion on this PR seems orthogonal to the commits history. However, I edited the first comment to refer to the original commit if was based on.

**Comment by olaurino** [comment]
@DougBurke I know you already labeled this PR for being merged, but I would like to get one more OK from you and then merge it.

**Comment by DougBurke** [comment]
I've checked this out (both as is and after merging into `master` so that I can try out the new testing infrastructure). Looks good. One change that should be made is to mention astropy as the primary choice in `README.md`. I think I'd say `astropy` is preferred but `pyfits` will also work (but is deprecated).

**Comment by olaurino** [comment]
@DougBurke do the changes to the README look good?

**Comment by DougBurke** [comment]
Looks fine to me.

**Comment by DougBurke** [comment]
Now that this has been merged, we should replace `pyfits` by `astropy` in the travis ci test (and probably can remove the cxc binstar channel from the setup too).

**Comment by olaurino** [comment]
@DougBurke I am thinking of adding a build with astropy rather than replacing the one with pyfits. Would you think that's overkill? It does not matter too much now, but when we start adding builds to the matrix this choice may double the number of builds.

**Comment by DougBurke** [comment]
For now I think it's fine. Once we start including different numpy versions we can decide if we want to remove the pyfits build.

**Pull request merged**
