### PR TITLE
rfe plot pvalue

### PR DESCRIPTION
**Pull request by dtnguyen2**
# Release Note

# Description
Handle the case given in:
https://icxc.harvard.edu/pipe/sherpadev/2018/0510.html

### CODE REVIEW

**Comment by dtnguyen2** [comment]
Apparently only I can see the following mail search:

 https://mail.google.com/mail/u/0/#search/plot_pvalue/KtbxLthZkHGvbcJQtVBTCwVlTJshlgqcBq

so I'm resending the aforementioned thread so it can be seen (I think) by everyone:

https://icxc.harvard.edu/pipe/sherpadev/2018/0462.html

Will update when more data and scripts (psf, etc...) are made available by SDS

**Comment by olaurino** [comment]
Rebasing and force-pushing to solve a conflict in the submodule

**Comment by olaurino** [comment]
Hmm... something is still wrong...

**Comment by olaurino** [comment]
It looks like github was confused... there was no conflict to begin with.

**Pull request merged**
