### PR TITLE
fix issue#788, fit using moncar with verbose=1 and/or numcores!=1

### PR DESCRIPTION
**Pull request by dtnguyen2**
# Note
fix issue#788, fit using moncar with verbose=1 and/or numcores!=1

### CODE REVIEW

**Comment by anetasie** [comment]
@dtnguyen2 there was another issue with the option setting in `moncar` related to `population_size`. For the 2 parameters the `population_size=5` or less results in sherpa 'hanging'
`ctrl-c` does not stop fit, and the only way to stop the process is to kill sherpa session, so `ctrl-z` and `kill`. 

```
set_method_opt('population_size',5)                                                                   

sherpa In [56]: fit()                                                                                                 
```

The higher numbers work fine.

**Comment by dtnguyen2** [comment]
script and data that you used?

**Comment by anetasie** [comment]
data in `\data\sherpa\aneta\Optimization`

```
load_data('q1127_src1.pi')
ignore(None,0.3)
ignore(7., None)

set_model('xsphabs.abs1*xszphabs.zabs*xspowerlaw.p1')
set_par('abs1.nh',0.07)
set_par('zabs.redshift',1.1)
set_par('zabs.nh',0.17)
freeze(zabs,abs1)
set_stat('chi2datavar')
set_method('moncar')
subtract()

set_method_opt('population_size',5)
fit()
```

**Comment by anetasie** [comment]
@dtnguyen2 `verbose' issue is fixed. I can confirm that I get screen output when run with verbose set to 1.

`population_size` is not fixed. I will open a separate issue.

**Comment by anetasie** [comment]
@dtnguyen2 - my test was run in your branch and confirmed the fix to `verbose`

**Pull request merged**
