### PR TITLE
WIP Remove excess brackets

### PR DESCRIPTION
**Pull request by DougBurke**
# Summary

Remove mathematically un-necessary brackets when displaying a model expression.

The code is there but more tests need adding and some clean up may be possible

The main problem at this time is that "a - (b - c)" gets converted to "a - b - c", which is not-quite-right™.

# Details

The `name` field of the `sherpa.models.model.Model` class is changed so that

- it is now a property (terminology?)
- the supplied value is stored as _name (and currently unused)
- access to `name` will now call the `sherpa.models.token.simplify` routine to be called on the stored model

The `simplify` routine is the routine that removes excess brackets, and is described below. Note that sub-classes of `Model` can override the `name` attribute so that you can have logic like (from `sherpa.astro.insrument` classes deriving from `CompositeModel`):

        CompositeModel.__init__(self, f'apply_rmf(apply_arf({model.name}))', (model,))

Although how this actually works is actually surprising to me, since this ends up setting the `_name` field which isn't then used. So I need to go back and review it, but it does seem to work... It also probably explains why some brackets have not been removed in the `get_model` output below.

TODO.

The basic idea is taken from https://stackoverflow.com/questions/18400741/remove-redundant-parentheses-from-an-arithmetic-expression

# Concerns

The logic is hidden away (the user doesn't interact with it), but it is technically possible for this to either break code (some condition isn't followed leading to a perfectly-valid expression to error out) or it removes a bracket that it shouldn't have. The latter is more concerning, as there's several parts to this work which means it isn't an easily-verified algorithm. My approach is to add a bunch of tests to catch possible problems. It would be nice to use some form of fuzzing or property testing approach.

# Example

Here's a source expression with a lot of terms in the current code:

```
sherpa In [3]: get_source()
Out[3]: <BinaryOpModel model instance '((xsconstant.m1 * xstbabs.m2) * ((((((((((((((((((((xsbremss.m3 + xsbremss.m4) + xsbremss.m5) + xsbremss.m6) + xsgaussian.m7) + xsgaussian.m8) + xsgaussian.m9) + xsgaussian.m10) + xsgaussian.m11) + xsgaussian.m12) + xsgaussian.m13) + xsgaussian.m14) + xsgaussian.m15) + xsgaussian.m16) + xsgaussian.m17) + xsgaussian.m18) + xsgaussian.m19) + xsgaussian.m20) + xsgaussian.m21) + xsgaussian.m22) + xsgaussian.m23))'>

sherpa In [4]: get_source().name
Out[4]: '((xsconstant.m1 * xstbabs.m2) * ((((((((((((((((((((xsbremss.m3 + xsbremss.m4) + xsbremss.m5) + xsbremss.m6) + xsgaussian.m7) + xsgaussian.m8) + xsgaussian.m9) + xsgaussian.m10) + xsgaussian.m11) + xsgaussian.m12) + xsgaussian.m13) + xsgaussian.m14) + xsgaussian.m15) + xsgaussian.m16) + xsgaussian.m17) + xsgaussian.m18) + xsgaussian.m19) + xsgaussian.m20) + xsgaussian.m21) + xsgaussian.m22) + xsgaussian.m23))'

sherpa In [5]: get_model()
Out[5]: <RSPModelPHA model instance 'apply_rmf(apply_arf((49922.938362591 * ((xsconstant.m1 * xstbabs.m2) * ((((((((((((((((((((xsbremss.m3 + xsbremss.m4) + xsbremss.m5) + xsbremss.m6) + xsgaussian.m7) + xsgaussian.m8) + xsgaussian.m9) + xsgaussian.m10) + xsgaussian.m11) + xsgaussian.m12) + xsgaussian.m13) + xsgaussian.m14) + xsgaussian.m15) + xsgaussian.m16) + xsgaussian.m17) + xsgaussian.m18) + xsgaussian.m19) + xsgaussian.m20) + xsgaussian.m21) + xsgaussian.m22) + xsgaussian.m23)))))'>
```

and here's how it displays in this PR

```
In [7]: get_source()
Out[7]: <BinaryOpModel model instance 'xsconstant.m1 * xstbabs.m2 * (xsbremss.m3 + xsbremss.m4 + xsbremss.m5 + xsbremss.m6 + xsgaussian.m7 + xsgaussian.m8 + xsgaussian.m9 + xsgaussian.m10 + xsgaussian.m11 + xsgaussian.m12 + xsgaussian.m13 + xsgaussian.m14 + xsgaussian.m15 + xsgaussian.m16 + xsgaussian.m17 + xsgaussian.m18 + xsgaussian.m19 + xsgaussian.m20 + xsgaussian.m21 + xsgaussian.m22 + xsgaussian.m23)'>

In [8]: get_source().name
Out[8]: 'xsconstant.m1 * xstbabs.m2 * (xsbremss.m3 + xsbremss.m4 + xsbremss.m5 + xsbremss.m6 + xsgaussian.m7 + xsgaussian.m8 + xsgaussian.m9 + xsgaussian.m10 + xsgaussian.m11 + xsgaussian.m12 + xsgaussian.m13 + xsgaussian.m14 + xsgaussian.m15 + xsgaussian.m16 + xsgaussian.m17 + xsgaussian.m18 + xsgaussian.m19 + xsgaussian.m20 + xsgaussian.m21 + xsgaussian.m22 + xsgaussian.m23)'

In [9]: get_model()
Out[9]: <RSPModelPHA model instance 'apply_rmf(apply_arf(49922.938362591 * (xsconstant.m1 * xstbabs.m2 * (xsbremss.m3 + xsbremss.m4 + xsbremss.m5 + xsbremss.m6 + xsgaussian.m7 + xsgaussian.m8 + xsgaussian.m9 + xsgaussian.m10 + xsgaussian.m11 + xsgaussian.m12 + xsgaussian.m13 + xsgaussian.m14 + xsgaussian.m15 + xsgaussian.m16 + xsgaussian.m17 + xsgaussian.m18 + xsgaussian.m19
+ xsgaussian.m20 + xsgaussian.m21 + xsgaussian.m22 + xsgaussian.m23))))'>
```

Note it's not perfect, since `texp * (m1 * m2 * ...)` could be simplified to `texp * m1 * m2 * ...`

### CODE REVIEW

**Comment by hamogu** [comment]
It would be nice, but is certainly not in scope for this PR, to have a graphical representation of the model tree.

**Comment by dtnguyen2** [comment]
Once the expression is parse, one can use
[use trelib?](https://treelib.readthedocs.io/en/stable/examples.html)

**Comment by DougBurke** [comment]
Note to self - the kind of thing I was thinking about with this PR is in the same area as https://github.com/FPtje/GLuaFixer/pull/114 (although I've only just seen this now and haven't dug into it) - and yes, I was using Haskell to prototype this...

**Comment by DougBurke** [comment]
Rebased just to catch up on recent changes - and made it rely on #1672 as otherwise it would have conflicted

**Comment by DougBurke** [comment]
Replaced by the much-simpler

- #1972

**Pull request closed without merging**
