### PR TITLE
Improve documentation of the pyBLoCXS code

### PR DESCRIPTION
**Pull request by DougBurke**
# Release Notes

Update the documentation to include more information about the pyBLoCXS code.

# Notes

Information has been added from the pyblocks ahelp file and website.
Numerous minor clean up and adjustments have been made to the documentation
of related functions.

### CODE REVIEW

**Comment by anetasie** [comment]
"The ``sherpa.sim`` module provides support for estimating the credible
interval of parameters in a fit to low-count data"

This statement should not refer to 'credible intervals'. The MCMC is more general than that and it should probably be changed to "explore posterior probability density" .

I'll probably will have more comments after reading the text.

**Comment by anetasie** [comment]
lines 344-348

the hard limits are used by get_draws, which will happen for "flat" distributions within soft limits,  so in order to restrict the runs the hard limits needs to be updated.

**Comment by anetasie** [comment]
line 446 - MH description 

I like to underlined that the jumps are ALWAYS from the best fit location here, so maybe add "always" into this sentence

**Comment by olaurino** [comment]
I am OK with merging this PR, although we should wait for PR #94 to be merged first.

**Comment by olaurino** [comment]
Hold on... @DougBurke were the comments by @anetasie taken into account? It does not seem so.

**Comment by DougBurke** [comment]
I've just addressed the comments from @anetasie and added an acknowledgements section

**Pull request merged**
