### PR TITLE
Release/4.8.2

### LINKED ISSUE #232: Problems building astropy after installing sherpa conda package
There's an issue if you install sherpa from conda - e.g.

    conda install -c https://conda.binstar.org/sherpa sherpa

and then try to build astropy (or at least the astropy-sherpa GSOC code) you can see errors like

```
... 
clang -fno-strict-aliasing -I/Users/secretuser/anaconda/envs/astropy_with_sherpabrigde/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DECHO -DWCSTRIG_MACRO -DASTROPY_WCS_BUILD -D_GNU_SOURCE -DNDEBUG -UDEBUG -I/Users/secretuser/anaconda/envs/astropy_with_sherpabrigde/lib/python2.7/site-packages/numpy/core/include -Icextern/wcslib/C -Iastropy/wcs/include -I/Users/secretuser/anaconda/envs/astropy_with_sherpabrigde/include/python2.7 -c cextern/wcslib/C/flexed/wcsbth.c -o build/temp.macosx-10.6-x86_64-2.7/cextern/wcslib/C/flexed/wcsbth.o -Wno-strict-prototypes -Wno-unused-function -Wno-unused-value -Wno-uninitialized
In file included from wcsbth.l:120:
In file included from cextern/wcslib/C/wcshdr.h:1149:
In file included from cextern/wcslib/C/wcs.h:1493:
cextern/wcslib/C/lin.h:599:8: error: redefinition of 'linprm'
struct linprm {
       ^
/Users/secretuser/anaconda/envs/astropy_with_sherpabrigde/include/wcslib.h:292:8: note: previous definition is here
struct
...
wcsbth.l:512:23: error: no member named 'cdelt' in 'struct wcsprm'
          vptr    = &(wcstem.cdelt);
                      ~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: command 'clang' failed with exit status 1
```

The short-term fix is to install astropy *before* sherpa (I think, @olaurino can confirm) but a fix to the build is needed to stop Sherpa from installing some .h files.

### LINKED ISSUE #241: `plot_photon_flux` function not working
I found this issue while working on the Python 3 migration, but this must be an old one, as I could reproduce it in CIAO 4.8 with Python 2.7.

Here is how to reproduce it:

````
In [1]: from sherpa.astro.ui import *

In [2]: load_pha('/export/working/sherpa/sherpa-test-data/sherpatest/3c273.pi')
WARNING: systematic errors were not found in file '/export/working/sherpa/sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file '/export/working/sherpa/sherpa-test-data/sherpatest/3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file /export/working/sherpa/sherpa-test-data/sherpatest/3c273.arf
read RMF file /export/working/sherpa/sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file '/export/working/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file '/export/working/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file /export/working/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi

In [3]: set_source("powlaw1d.p")

In [4]: fit()
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
Dataset               = 1
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 8.15838e+10
Final fit statistic   = 50.5351 at function evaluation 25
Data points           = 46
Degrees of freedom    = 44
Probability [Q-value] = 0.231118
Reduced statistic     = 1.14852
Change in statistic   = 8.15838e+10
   p.gamma        1.72329
   p.ampl         0.000147339

In [5]: plot_photon_flux()
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-c9e1b71329e2> in <module>()
----> 1 plot_photon_flux()

<string> in plot_photon_flux(lo, hi, id, num, bins, correlated, numcores, bkg_id, **kwargs)

/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.pyc in plot_photon_flux(self, lo, hi, id, num, bins, correlated, numcores, bkg_id, **kwargs)
  10993         if sherpa.utils.bool_cast(kwargs.pop('recalc', True)):
  10994             pfplot = self._prepare_photon_flux_plot(pfplot, lo, hi, id, num,
> 10995                                                     bins, correlated, numcores, bkg_id)
  10996         try:
  10997             sherpa.plot.begin()

/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.pyc in _prepare_photon_flux_plot(self, plot, lo, hi, id, num, bins, correlated, numcores, bkg_id)
   9911     def _prepare_photon_flux_plot(self, plot, lo, hi, id, num, bins, correlated, numcores, bkg_id):
   9912         dist = self.sample_photon_flux(
-> 9913             lo, hi, id, num, correlated, numcores, bkg_id)
   9914         plot.prepare(dist, bins)
   9915         return plot

/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.pyc in sample_photon_flux(self, lo, hi, id, num, scales, correlated, numcores, bkg_id)
  11274                                              sherpa.astro.utils.calc_photon_flux,
  11275                                              correlated, num, lo, hi, numcores,
> 11276                                              scales)
  11277
  11278     # DOC-TODO: should this accept the confidence parameter?

/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/flux.pyc in sample_flux(fit, data, src, method, correlated, num, lo, hi, numcores, samples)
     74             samples = samples.diagonal(0)
     75
---> 76     samples = sampler.get_sample(fit, samples, num=num)
     77
     78     hardmins = fit.model._get_thawed_par_hardmins()

/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/sim/sample.pyc in get_sample(self, fit, myscales, num)
    257     def get_sample(self, fit, myscales=None, num=1):
    258         vals = numpy.array(fit.model.thawedpars)
--> 259         scales = self.scale.get_scales(fit, myscales)
    260         samples = [numpy.random.normal(
    261             val, scale, int(num)) for val, scale in izip(vals, scales)]

/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/sim/sample.pyc in get_scales(self, fit, myscales)
    167             if not numpy.iterable(myscales):
    168                 raise TypeError(
--> 169                     "scales option must be iterable of length %d " % len(thawedpars))
    170             scales = map(abs, myscales)
    171         scales = numpy.asarray(scales).transpose()

TypeError: scales option must be iterable of length 2
````

### PR DESCRIPTION
**Pull request by olaurino**
# Notes
Release branch for 4.8.2 release.

This release also fixes #241 (through #252) and the conda binaries will fix #232.

# Notes
This branch has been obtained by merging #252, i.e. the release branch for CIAO 4.9b1.5. The expectation is that the CIAO release branch will be merged into master first.

Also, this PR assumes that #221 is merged into master, although at this point this only happened on my local repo.

### CODE REVIEW

**Comment by DougBurke** [comment]
I thought I'd added a note by email, but it doesn't want to show up here, so I'm re-typing it in case it's got lost.

Does it make sense to move our conda recipes to [conda-forge](https://conda-forge.github.io), so that we get "builds for free"? Or is the environment they provide/support not up to the task?

**Comment by olaurino** [comment]
I haven't had time to look into conda-forge yet, although it is certainly promising. There is a chance their environment does not have all our dependencies, but there is only one way to find out and it takes time to try.

**Comment by DougBurke** [comment]
I was hoping that 8a368f1 was going to stop the pytest-warning (mainly because on my terminal at work it ends up being yellow on a white background, which is hard to read), but it looks like we're still seeing it: e.g. https://travis-ci.org/sherpa/sherpa/jobs/160141187#L4918

Am I mistaken about the change in 8a368f1 then?

**Comment by olaurino** [comment]
I believe the pytest warning would be resolved by enclosing 'sherpa' in square brackets here:
https://github.com/sherpa/sherpa/blob/master/helpers/test.py#L53

**Comment by DougBurke** [comment]
I'm sure that's a meaningful cange to the pytest folks ;-)

**Comment by DougBurke** [comment]
Going back to conda-forge, if they can have one for scipy - e.g. https://github.com/conda-forge/scipy-feedstock - then we should be okay (in the infinite-free-time future we live in where we can try this out ;-)

**Comment by olaurino** [comment]
@DougBurke do you know what triggers builds in conda-forge? When do the packages actually get built?

**Comment by DougBurke** [comment]
From https://conda-forge.github.io/index.html#contribute it looks like you set up you "feedstock" and then things get built whenever there's a push to that repository. They only get accepted/moved to the channel once the feedstock has been "accepted" (and then you go through PRs on this feedstock to get changes accepted). Or at least that's my understanding from a not-very-thorough reading of this page!

**Comment by DougBurke** [comment]
I thought we were going to re-install  43b3791 - but I see it has still been reverted in this PR.

**Comment by olaurino** [comment]
It looks like this PR is going to be merged before #252, which means #252 will be merged automatically as part of this PR. This is not an issue, I'll leave the branch on GitHub in case CIAO CM needs new builds, and we can recreate the PR if anything needs to be fixed in the CIAO 4.9b1.5 release (unlikely, at this point).

@DougBurke sorry about 43b3791, I got caught into build/test issues and never added that commit. Given that we need some changes in order to upload the source code to PyPI, we'll make sure to update `setup.py` when we are ready for that.

**Pull request merged**
