### PR TITLE
Simplify implementation of pyfits backend

### LINKED ISSUE #841: refactor pyfits_backend with modern astropy functionality?
The pyfits backend as written in the era of pyfits and it does well what it does. However, pyfits became part of astropy about 8 years ago and today we import the fits code from astropy. That means the every time we use that backend, we also have the full astropy available, and quite some of the code in `pyfits_backend.py` duplicates existing astropy code, in particular `astropy.table.Table` (for reading and writing tables like PHA) and `astropy.wcs` (for all the wcs stuff in the pyfits backend) come to mind. 

On the one hand, I'm reluctant to change anything that's not broken and that relies only on very stable code, i.e. astropy >= 0.4 should be good enough (the pyfits interface has been stable since before astropy, while e.g. Table and WCS have changed in the past but are quite mature now), on the other hand, I know that astropy handles quite a few corner cases and extras that we don't have in this code, e.g. reading of Tables over https instead of a local file.

@DougBurke : Thoughts?

### PR DESCRIPTION
**Pull request by hamogu**
These are the general steps that we can take to reduce the code:

- replace table writing with the `astropy.table.Table` interface
- replace table reading with the same interface
- Can we use `astropy.wcs` instead of the WCS implemented here?

At least as of now, this implemenation is not identical to pycrates
any longer, e.g.
- an astropy specific warning is emitted for file operations
  (e.g. file not found, clobber=False and file exists).
  I think that's OK.
- The creates backend automatically tries to add ".gz" if the filename
  is not found. That requires and extra try .. except that I did not
  put in yet (maybe as a decorator for file reading functions)
- Should header be written? Should keywords that are None be written?
  The pyfits code has opinions on this, this implementation simply
  chooses the path of least resistance. If really needed, thos could be
  added back in.

This is a WIP, I'm putting it up here for general discussion and so I
don't forget. The reason I'm looking at this at all (why youch working code?)
is that I needed and ARF/RMF reader/writer for a different project and was
hoping to use the implementation that's alrady in Sherpa. So, I had to
understand what's in here first.

Also related to
- #1070 (at least astropy table can read from URLs and
  read/write to streams).
- #878

closes #841

Note: We could always leave the pyfits backend untouched (safe!) and move
this to a new backend "astropy". That way we can collect some real world
experience and see if it breaks too much. While I don't think we should
maintain both pyfits backend and this indefinitely, there is little harm
in having both for an extended pariod of time (assuming I ever finish this PR!)

Todo

- [ ] Table reading (especially RMF/ARF!)
- [ ] image reading / writing
- [ ] modify tests because this throws different exceptions now (but may we don't have to text all branches any longer, since astropy itself tests, e.g. that overwrite=False does not overwrite an existing file.

### CODE REVIEW

**Comment by DougBurke** [comment]
I have been mulling over renaimg the `pyfits` backend to `astropy` with a fall-through case, but I think having an all-new `astropy` backend sounds like fun.

**Comment by DougBurke** [comment]
Also the test failures are tracked in #1090 (at least the ones unrelated to this PR ;-)

**Comment by DougBurke** [comment]
Looks like this needs rebasing now that #1092 has been merged, which will hopefully fix the test failures.

**Comment by hamogu** [comment]
This has been overtaken by work by @DougBurke -see #1939. Some of the changes here might still be useful as reference, but it's going to be easier to wrote from scratch then to adapt this, so I'm closing.

**Pull request closed without merging**
