### PR TITLE
Add unsubtract and ungroup to datastack

### PR DESCRIPTION
**Pull request by hamogu**
# Summary

Since the datastack has a "subtract" method, it should have the matching
"unsubtract" method and the same for group/ungroup.

# Note
Note that the datastack is not documented within this repro, so the
relevant ahelp page has to be updated separately.

### CODE REVIEW

**Comment by DougBurke** [comment]
I think out current test coverage of the datastack module isn't great. These routines should be relatively easy to add tests to in `sherpa/astro/datastack/tests/test_datastack.py`

**Comment by hamogu** [comment]
@dtnguyen2 Test added, checks pass except for the spurious codecov failure due ot random tests in brag_bayes that have nothing to do with this PR and that we discussed yesterday.

**Comment by DougBurke** [comment]
@hamogu - those tests look like the sort of thing we'd want - thanks!

**Comment by hamogu** [comment]
@dtnguyen2 : Just waiting for your review. CI failure is from a problem how codecov is set up and has nothing to do with this PR.

**Review by dtnguyen2 — APPROVED** [review]

**Review by wmclaugh — APPROVED** [review]

**Pull request merged**
