### PR TITLE
Improve documentation for notice2d

### LINKED ISSUE #1059: Docs: notice2d and related don't mention/link to set_coord
I had forgotten what set_coord was called and the help page was no use...

### PR DESCRIPTION
**Pull request by DougBurke**
# Summary

Minor improvements to the documentation of notice2d and ignore2d set of commands. Fixes #1059

# Details

Add set_coord to the see-also section of the notice/ignore2d routines. Add an example of using set_coord to the notice2d examples.

Add a note about the support for the REGION specifier, which is apparently CIAO-only.

### CODE REVIEW

**Comment by DougBurke** [comment]
You can see the new documentation at https://sherpa--1082.org.readthedocs.build/en/1082/ui/api/sherpa.astro.ui.notice2d.html and compare it to the existing docs at https://sherpa.readthedocs.io/en/4.13.0/ui/api/sherpa.astro.ui.notice2d.html

The main aim was to add set_coord to the see-also section.

**Review by anetasie — COMMENTED** [review]
This is not supported ``region(s1.reg)+region(s2.reg)``

But is  'circle()+circle()' supported if it is a part of s1.reg?

This works as well
notice2d('circle(4324.2,3827.5,40)+circle(4400.2,3900,40)
It might be good to add such examples.

**Comment by DougBurke** [comment]
I believe that 

```
% cat a.reg
circle(....)+circle(...)
```

and then

```
>>> notice2d('a.reg')
```

is supported, but I don't have time to test that assumption.

**Comment by anetasie** [comment]
I tested notice2d(circle()+circle(0) which works

**Comment by DougBurke** [comment]
I'm confused. THere's already a whole section of the docs about how you can say 'notice2d(shape+shape)', and an example, so I'm not sure why you were asking about it.

**Comment by anetasie** [comment]
@DougBurke I missed the description, forgot to click through the whole section.

**Comment by DougBurke** [comment]
@anetasie is this ready to get merged or do you think we need more changes?

**Comment by DougBurke** [comment]
@anetasie is this ready to get merged or do you think we need more changes?

**Review by anetasie — APPROVED** [review]

**Pull request merged**
