### PR TITLE
Continue S-Lang removal

### PR DESCRIPTION
**Pull request by DougBurke**
# Release Note
Removed S-Lang scripts, files, and references in the code.

# Description
I forgot to include this in PR #69.
[OL] Rebased and included Release Note section.

### CODE REVIEW

**Comment by olaurino** [comment]
I guess we can label it for merging (as long as Travis agrees, just in case) ;-)

**Comment by DougBurke** [comment]
I removed pr:merge as I've just added another change which is a bit-more significant.

**Comment by olaurino** [comment]
Since there are conflicts, I am currently rebasing this branch onto the latest master.

The conflicts are merely the result of pep8 clean-ups that have happened on master while this PR was open.

If everything, including the Travis CI builds, looks OK after the rebase, I am OK with merging this.

**Comment by olaurino** [comment]
@DougBurke I would just like you to sign off on the new commits as you are the original author. If you think everything looks the way you intended, we can label it to merge.

**Comment by DougBurke** [comment]
Looks fine to me.

:shipit:

**Pull request merged**
