### PR TITLE
revert PR #444 (caching)

### PR DESCRIPTION
**Pull request by dtnguyen2**
# Summary

Revert the ARF cache added in #444, as well as some of the related code changes, as they caused problems (e.g. #746)

# Note 

This PR reverts part of PR #444

### CODE REVIEW

**Comment by dtnguyen2** [comment]
PR #733 should still be considered to be merged to enable setting the Boolean ```cache``` option at runtime

**Comment by DougBurke** [comment]
@dtnguyen2 - this leaves in some of the changes from #444, so I've edited the description.

**Comment by DougBurke** [comment]
I checked and with the data from #746 the fit now works

```
In [9]: ui.fit(10)
WARNING: data set 10 has associated backgrounds, but they have not been subtracted, nor have background models been set
Dataset               = 10
Method                = levmar
Statistic             = cstat
Initial fit statistic = 43.2211
Final fit statistic   = 2.57681 at function evaluation 14
Data points           = 32
Degrees of freedom    = 31
Probability [Q-value] = 1
Reduced statistic     = 0.0831231
Change in statistic   = 40.6443
   line.ampl      19.7173      +/- 6.28794

In [10]: ui.plot_fit(10)
WARNING: The displayed errorbars have been supplied with the data or calculated using chi2xspecvar; the errors are not used in fits with cstat

In [11]: ui.calc_stat()
WARNING: data set 10 has associated backgrounds, but they have not been subtracted, nor have background models been set
Out[11]: 2.5768146402448835
```

works

**Comment by dtnguyen2** [comment]
PR #759 removed the ARF caching code so this is no longer relevant and therefore should be closed

**Pull request merged**
