### PR TITLE
Set up travis-ci

### PR DESCRIPTION
**Pull request by cdeil**
First of all, it's great that Sherpa is on Github now, thank you!

How about setting up https://travis-ci.org/ for continuous testing of Sherpa?
I've done this for a few Python packages, so I could make a pull request adding the `.travis.yml` file.
But an admin for the Sherpa Github repo has to activate builds on travis-ci as described [here](http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in) ... it just takes a minute.

### CODE REVIEW

**Comment by olaurino** [comment]
@cdeil thanks for volunteering, but keep in mind that I am already working on the travis-ci configuration, since I already have experience with both travis and setting an environment for testing sherpa on virtual workers. After I set up a basic configuration we can complicate it at will (e.g. by testing with different versions of numpy).

We do not support windows. I tried building Sherpa for windows on a weekend at some point, and it should not be terribly difficult to support this platform, but that's a project of its own and we never got this request, so that's unlikely to happen (at least on our side). If somebody wanted to try, I can share by notes on the windows build.

On the other hand, I will see if I can enable OSX testing, and your experience with setting it up for Astropy will be beneficial.

As for the Python 3 support, it's a big project. Not only the pure Python part of Sherpa needs to be updated, but also all the C and Fortran extensions need to be ported. I am not saying it's not going to happen, just that it can't happen overnight.

**Comment by cdeil** [comment]
@olaurino – I didn't know you are setting up a travis-ci test. Great! We can just close this PR once that's done.

**Comment by olaurino** [comment]
@cdeil thanks for the commits, they certainly help. May I ask if you tested them?

**Comment by cdeil** [comment]
I just copied the files from the Astropy repo in the first commit and made some obvious edits in the second commit. I didn't do any testing and as you can see, the travis-ci build fails. Now if I were to do it, I'd just repeatedly edit `.travis.yml` until all builds pass, or, if I run into weird errors I don't understand, try to reproduce the error locally (see notes [here](https://github.com/gammapy/gammapy/blob/master/dev/docker/commands.sh)).

Let me know if there's anything I can help with here (although I'm offline now for a few hours).

**Comment by olaurino** [comment]
sorry, I made a stupid question... I should have gone to lunch before commenting ;)

**Comment by olaurino** [comment]
This PR is replaced by PR #31. Closing. Thanks @cdeil for the contributions! I hope to get your feedback on #31.

**Pull request closed without merging**
