### PR TITLE
Add UI type annotations

### PR DESCRIPTION
**Pull request by DougBurke**
An example of adding type annotations to try out #1501. What is interesting (in this particular work) is what "interfaces" we end up relying on. There are a number of cases where we basically want to say "we return an object that follows this interface" but our current setup isn't designed like this (we don't really use metaclasses to create protocols/interfaces, instead rely on just straight subclasses. Does this suggest that we might want to use a more metaclass approach, or is it worth not breaking things that aren't broken.

I have been using `mypy` to validate this, (I have now tried with `mypy` using python 3.10 and 3.7). However, even with a number of methods annotated I am not convinced this has correctly caught the best type annotations. I expect that there can be some places where annotating a new method/module may cause a number of related changes to existing annotations. There's also some functionality in 3.10 (or later) that may be helpful (eg type guards), that we could think about requiring type_extensions.

One interesting thing to think about from this work, as it deals with the ui layer, is that we have routines like

    def set_model(id, model=None):

(dropping the `self` argument for exposition) which can actually be used as

    set_model(a_model)
    set_model(idval, a_model)

that is, even though the first argument is labelled `id` it is actually somewhat amorphous in its meaning: if only one argument is given it actually means the `model` argument and the default `id` is used, but if two positional arguments are given then the first argument is the `id`. I decided I didn't want to deal with that in my first play around.

This is based on #1524 #1516 #1513 - currently only the last commit is actually part of this PR
 
I will note that `sherpa/ui/uitils.py` will not validate via `mypy` but that's mnot my fault as it is an existing bit of code and it is rather low-level so I don't feel like worrying about it just yet:

```
% mypy sherpa/ui/utils.py 
sherpa/ui/utils.py:185: error: Argument 1 to "constructor" has incompatible type "Callable[[Any, Any], Any]"; expected "Callable[[Union[Tuple[Callable[..., Any], Tuple[Any, ...]], Tuple[Callable[..., Any], Tuple[Any, ...], Optional[Any]]]], Any]"
Found 1 error in 1 file (checked 1 source file)
```

### CODE REVIEW

**Comment by DougBurke** [comment]
One thing I wanted to look at was the noise this could add to the RTD documentation (although it's not much different to the `help` output, really). Here's

- a routine that hasn't been annotated



- routines that have been annotated

screenshot1
screenshot2
screenshot3
screenshot4

**Comment by hamogu** [comment]
I have to admit I'm not yet convinced that essentially static typing with worth it in general in a code like sherpa, in particular for the ui stuff where `id` can be given or not as first argument. The "Union[xxx, yyy]" also does not look great to the eye - but maybe I just have to get used to it. 

Re - fixing stuff that's not broken: Even if that was nice, we probably have enough to do. 

So, I do wonder (but have no idea really) (1) if there are limited areas where we can profit from this, (2) if we just add it as we fancy, or (3) just don't do that at all.

**Comment by DougBurke** [comment]
Note to self:

we can add support for copying over annotations, so that after `from sherpa.astro.ui import *` we can see the annotations either with `help` or on RTD, but there do appear to be limitations (we have access to the type synonyms that are used, which means these get copied rather than the underlying `List[Union[int, str]]` type it represents). Python 3.10 also changes/simplifies things, so it's not obvious if this works nicely with earlier code.

```
% git diff .
diff --git a/sherpa/utils/__init__.py b/sherpa/utils/__init__.py
index 3890aa04..47ca8b7e 100644
--- a/sherpa/utils/__init__.py
+++ b/sherpa/utils/__init__.py
@@ -1138,8 +1138,7 @@ def bool_cast(val):
 
 
 def export_method(meth, name=None, modname=None):
-    """
-    Given a bound instance method, return a simple function that wraps
+    """Given a bound instance method, return a simple function that wraps
     it.  The only difference between the interface of the original
     method and the generated function is that the latter doesn't
     include 'self' in its argument list.  This means that when the
@@ -1157,6 +1156,11 @@ def export_method(meth, name=None, modname=None):
     function.  Note that the caller is responsible for assigning the
     returned function to an appropriate name in the calling scope.
 
+    Annotations are copied over if available. With all the changes in
+    annotation support in Python 3.10 it is not at all obvious if this
+    is sufficient or will work with the currently-supported Python
+    verions.
+
     """
 
     if type(meth) is not MethodType:
@@ -1207,6 +1211,13 @@ def export_method(meth, name=None, modname=None):
                             new_meth.__closure__)
     new_meth.__doc__ = doc
 
+    # Can we support annotations? There are changes in Python 3.10,
+    # but for now just do the simplest thing in the hope it works.
+    #
+    annotations = getattr(meth, "__annotations__", None)
+    if annotations is not None:
+        new_meth.__annotations__ = annotations
+
     return new_meth
 
```

and

```
>> from sherpa.ui.utils import Session
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
>>> Session.list_data_ids.__annotations__
{'return': 'IdTypes'}
>>> help(Session.list_data_ids)

>>> from sherpa.ui.utils import IdTypes
>>> IdTypes
typing.List[typing.Union[int, str]]
>>> quit()
```

**Comment by hamogu** [comment]
https://numpy.org/devdocs/reference/typing.html

**Comment by DougBurke** [comment]
I'm leaving this open more as a discussion of things we've found out about typing rather than as something to merge. I should probably just take this and put the relevant info into an issue but ...

**Comment by DougBurke** [comment]
As time goes on this is getting more-complex to rebase, and not worth keeping aronud.

**Pull request closed without merging**
