### PR TITLE
Make __all__ a tuple

### PR DESCRIPTION
**Pull request by DougBurke**
Sphinx complains that `__all__` isn't a tuple.

I've also added 2015 to the copyright.

### CODE REVIEW

**Comment by DougBurke** [comment]
This is part of CXC ticket 13968.

**Comment by DougBurke** [comment]
I guess I really should also update the copyright in `sherpa/io.py`.

**Comment by cdeil** [comment]
@DougBurke – There's one more typo `_all__` with a missing underscore here: https://github.com/sherpa/sherpa/blob/master/sherpa/data.py#L35

**Comment by DougBurke** [comment]
@cdeil - thanks; fixed in commit @b5c4e22.

**Comment by olaurino** [comment]
I am going to rebase this one so that it gets built by Travis CI (and we reduce the commits history clutter). I don't expect any issues, and I reviewed the PR myself. As soon as Travis gives me the green light, I'll merge this one.

**Pull request merged**
