### PR TITLE
Add bokeh as a backend

### PR DESCRIPTION
**Pull request by hamogu**
# Status
This would profit from some real-live use to root out any problems before I'm finalizing the tests.

# Summary
This PR adds a [bokeh](https://bokeh.org/) plotting backend. Bokeh is a Python library that generates js output to be displayed in the browser. Those plots are interactive by default (e.g. zoom) and many more features are available (linking different panels, switching individual lines in the plot on and off, anything in js that we implement, e.g. dynamic binning in the plot even without a running python session). Interactive HTML/js plots can be embedded into AJ/ApJ articles, used in websites, interactive posters etc. 

The goal of this PR is simply to reproduce the main features of our matplotlib interface, advanced features can be added later. **Update**: In order to keep PRs managable and have them merged timely, I've decided to put "docs for how to write a backend" into a separate PR.

# Details

This is built on top of #1191 - testing and developing this is much easier with a way to switch the backend dynamically. At the same time, this acts as a test to #1191. It's all good to say that you've cleanly separated backends and backend-independent plotting code, but only with a second, fully functional backend you really know that that's true.

Give that I'm writing a second backend here, I'll also take the opportunity to write down the specs/API of how to do that.

Missing
- [ ] bokeh tests
- [x] narrative docs
- [ ] an example notebook

### CODE REVIEW

**Comment by DougBurke** [comment]
:1st_place_medal:

**Comment by DougBurke** [comment]
So, I haven't had the time to look at this, so it may be obvious from the commits, but our existing `_repr_html` code for Sherpa objects - so that they can display "nicely" in notebooks - have a number of places that check if the matplotlib backend is selected and, if so, returns a plot / image rather than a table. This sometimes takes advantage of the sherpa plot hierarchy - in which case we would want the code to just check that the backend is not the dummy backend, but in some places it just uses direct access to matplotlib functionality. I would assume these can be done with bokeh, so I was wondering whether you'd got to look at this code, or whether the notebook changes you talk about are really showing that `plot_data()` is now nicely interactive?

An example from a notebook with a PHA file loaded would be comparing

plot_data()

in one cell with the output of

get_data()

in another cell.

**Comment by hamogu** [comment]
I have not tried all possible cases (arf, rmf, ...), but here is one:

(sorry my screen is not large enough to show both plots in full at the same time)
Screen Shot 2021-12-03 at 1 56 27 PM

From what I have seen, the _repr_html_ generally works by calling XXX_as_html in the backend and the bokeh backend just implements those functions. (Although, in the interest of decoupling backends from plots, it would be useful to have a more general way of expressing that we we don't have to add one `as_html` function per lpottype to each backend. But that's a separate improvement.

**Comment by DougBurke** [comment]
Ta. I was just looking at the notebook tests (for #1374) and it reminded me that we should check things now we are moving to a glorious multi-plot-backend future.

Examples that I know are matplotlib-specific are RMF and image objects. The RMF version could be done via sherpa plots but it would miss some things (partly related to #938 but that is still backend-specific) and the image support would need #347 addressed.

For reference:

RMF plot: https://github.com/sherpa/sherpa/blob/a436ccf2478c83fa8628f556726d25de9f729ded/sherpa/astro/data.py#L685-L750

image plot: https://github.com/sherpa/sherpa/blob/a436ccf2478c83fa8628f556726d25de9f729ded/sherpa/astro/data.py#L753-L828

**Comment by hamogu** [comment]
Good point. I think the rmf plot can be made backend agnostic and a display for image objects #347 would be useful in a number of cases. Once that is added, it does not have to be special-cased here. I'm just trying to spin my hear around how to do all that and still have PRs that are small enough to actually review in practice. For once, I'll create a new project to track these. In our last meeting we discussed this to a lever that made clear that is is going to be more than a few isolated PRs. (And a project and easily be removed again if DS disagrees with that way of tracking.)

**Comment by DougBurke** [comment]
I do think the notebook changes are somewhat orthgonal to the "add-a-new-backend" changes, but they are part of the same project (particularly in terms of ensuring the backend abstraction is not-leaky).

**Comment by hamogu** [comment]
Yes, there are a number of orthogonal changes, but then they are also connected in some way. 
So, my goal is to next have a PR that defines the interface for a backend, by writing down a specification and offering a test module to test for "leakiness" in some cases. In practice, that's possible, but unnecessarily hard to do without using this PR (use a second functional backend to see what happens), so I'll probably have to rebase or adapt this a couple of times.

**Comment by hamogu** [comment]
While this is fully functional (despite needing rebasing now), I'm converting it to a draft since it's part of the larger plotting system overhaul that has not yet been approved in full.

**Comment by DougBurke** [comment]
So, as part of looking at #1382 (via the rebased #1550) I've been playing around this morning with adding an [altair](https://altair-viz.github.io/) backend, because the declarative model used by altair - which is basically the [Vega-Lite  schema](https://vega.github.io/vega-lite/) - is likely to break the assumptions that the existing backend assumes:

- how the visualization is created (e.g. the passing around of "objects" that create the plot and then are used to display the thing)
- creation of the plot elements

Although it is also a JS backend it is somewhat different to bokeh, so I'm interested to see the backend here currently uses "global state" to create the output (at some level this is always going to be the case, and it is just how well encapsulated it is).

My guess is that altair is not a good choice for sherpa, and I don't think we want to contort our API to make it work, but just wanted to mention this somewhere.

**Comment by hamogu** [comment]
Sherpa assumes that at plotting backend is stateful, i.e. you can add stuff one by one and the backend keeps track what the "active axis" is and stuff like that. `matplotllib.pyplot` does that, but bokeh does not, that's why this PR has lines like this https://github.com/sherpa/sherpa/pull/1356/files#diff-dbf59ad6ac809e580e0a31e3c990a87ab1692c7c08d3f4474784889235cddaeeR137 to emulate that behavior. Altair needs, at the lest, something similar. I think it could be made work if the plotting module "caches" previous plotting commands in a module-level variable and then combines them in some suitable way.

**Comment by DougBurke** [comment]
Yeah - I'm just thinking about #1729 and whether there's things we can do now to make things workable for "most" backends (but not making it so abstract that it's too hard to design and implement that we never do it). At the moment I quite like the approach in #1729 **but** maybe it's not worth it?

**Comment by hamogu** [comment]
closing in favor of #1899.

**Pull request closed without merging**
