### PR TITLE
comment out some time consuming tests

### PR DESCRIPTION
**Pull request by dtnguyen2**
# Release Note

Removed a few time consuming tests (test_SumSquares, test_Zakharov, test_Levy, test_Sphere).  The test should finish in reasonable time now

### CODE REVIEW

**Comment by DougBurke** [comment]
Can we have a brief comment added to say something like

>>> # test commented out as they take a long time to run, see https://github.com/sherpa/sherpa/pull/649

just so that when we look back at them in 2 years we know why they aren't in use. An alternative to commenting them out is to rename them so they don't begin with 'test_', and then the test harness won't run them, but they are available if you ever want to call them manually (although how you would do that via `pytest` is beyond my ken).

**Comment by dtnguyen2** [comment]
added comments as to why the tests were removed

**Comment by olaurino** [comment]
I'll add this to the 4.11.1 release as that will dramatically speed up the packaging/testing pipeline. The best thing would have been to mark the tests to be skipped unless a specific option is given. I don't have time for this, but somebody might want to do that in the future.

**Comment by olaurino** [comment]
Here is a pointer to the relevant documentation:
http://doc.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option

**Pull request merged**
