### PR TITLE
fix typo in startup script

### PR DESCRIPTION
**Pull request by olaurino**
# Description
After testing the new startup scripts in CIAOD I realized there was a typo in one of the updates startup scripts. This PR fixes the typo.

### CODE REVIEW

**Comment by olaurino** [comment]
@DougBurke do you think I can merge this?

**Comment by DougBurke** [comment]
So, just to check: this looks like it's fixing a typo you added recently (and we didn't pick up in our code review), rather than a bug in the code that's been there a long time?

Also, we don't have anything in the Travis-CI tests that checks that this code works. The testing for this happens off-to-the side since it's part of CIAO rather than the standalone release?

**Comment by olaurino** [comment]
Yes, and Yes.

**Comment by DougBurke** [comment]
Looks fine for merging.

**Pull request merged**
