### PR TITLE
load_table_model updates

### LINKED ISSUE #143: load_table_model unable to load FITS binary tables when using astropy and using the colkeys argument
**EDIT** it appears that this is related to using the `colkeys` argument to `load_table_model`, since it seems to work fine with a two-column FITS file.

It's not clear from the `load_table_model` documentation whether we support FITS binary tables, but I think we should. This is for the "simple" form, not the XSPEC table model support.

With CIAO 4.8 - using the crates I/O backend - you can load in a FITS binary table, but with astropy 1.1 it fails. Using the example from #142 - which I've placed at https://gist.github.com/DougBurke/c52db195adcc9b8701f1

```
% dmlist pl_gamma2.fits cols

--------------------------------------------------------------------------------
Columns for Table Block TABLE
--------------------------------------------------------------------------------

ColNo  Name                 Unit        Type             Range
   1   elo                               Real8          -Inf:+Inf            
   2   ehi                               Real8          -Inf:+Inf            
   3   emid                              Real8          -Inf:+Inf            
   4   mdl                               Real8          -Inf:+Inf  
```

In CIAO we get

```
% sherpa
-----------------------------------------------------
Welcome to Sherpa: CXC's Modeling and Fitting Package
-----------------------------------------------------
CIAO 4.8 Sherpa version 1 Thursday, December 3, 2015

sherpa-1> load_table_model('mdl', 'pl_gamma2.fits', colkeys=['emid', 'mdl'])
sherpa-2> print(mdl)
tablemodel.mdl
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   mdl.ampl     thawed            1 -3.40282e+38  3.40282e+38           
sherpa-3> 
```

but with master, I get

```
% ipython
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sherpa.astro import ui
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: ui.load_table_model('mdl', 'pl_gamma2.fits', colkeys=['emid', 'mdl'])
---------------------------------------------------------------------------
IOErr                                     Traceback (most recent call last)
<ipython-input-2-e6a2f5aea9b2> in <module>()
----> 1 ui.load_table_model('mdl', 'pl_gamma2.fits', colkeys=['emid', 'mdl'])

<string> in load_table_model(modelname, filename, method, *args, **kwargs)

/home/djburke/sherpa/sherpa-master/sherpa/astro/ui/utils.pyc in load_table_model(self, modelname, filename, method, *args, **kwargs)
   8981                 # more sophisticated I/O backend loaded (such as
   8982                 # pyfits or crates) SMD 05/29/13
-> 8983                 data = sherpa.io.read_data(filename, ncols=2)
   8984                 x = data.x
   8985                 y = data.y

/home/djburke/sherpa/sherpa-master/sherpa/io.pyc in read_data(filename, ncols, colkeys, sep, dstype, comment, require_floats)
    155 
    156     colnames, args, name = get_ascii_data(filename, ncols, colkeys,
--> 157                                           sep, dstype, comment, require_floats)
    158     return dstype(name, *args)
    159 

/home/djburke/sherpa/sherpa-master/sherpa/io.pyc in get_ascii_data(filename, ncols, colkeys, sep, dstype, comment, require_floats)
    123 
    124     if is_binary_file(filename):
--> 125         raise IOErr('notascii', filename)
    126 
    127     names, args = read_file_data(filename, sep, comment, require_floats)

IOErr: file 'pl_gamma2.fits' does not appear to be ASCII

In [3]: 
```

I haven't looked to see if this is due to the known astropy-backend issues, or a new one.

### PR DESCRIPTION
**Pull request by DougBurke**
# Status

I have closed this PR since the initial changes have made it in through other PRs and its gone back to development stage (in part because I don't have the time to work on it). I do expect these changes to make it back to a PR at some point in the future.

Not finished. PR is to get Travis-CI feedback on the changes.

# Release Notes

Improve documentation of `sherpa.ui.load_table_model`.

Improve documentation of the I/O related routines in `sherpa.ui` (remove mention of the Sherpa I/O module as this is not relevant here).

Enhance the test suite for `sherpa.ui.load_table_model` and apply PEP8 fixes. 

# Notes

I am planning to fix #143 but need to improve the current documentation and testing to make sure nothing breaks. 

**EDIT** I am breaking out some of the changes into separate PRs so that these improvements are not held up by a discussion of how to organize the tests (and improve them): #173 #174 #175

### CODE REVIEW

**Comment by DougBurke** [comment]
@olaurino  - the test failures are now in the build - so I think unrelated to this patch, so either an intermittent failure with the travis setup or some issue with a recent update: 

```
building 'sherpa.optmethods._minpack' extension
error: extension 'sherpa.optmethods._minpack' has Fortran sources but no Fortran compiler found
```

**Comment by olaurino** [comment]
I restarted the builds. Travis had some issues last night, but things should be OK now.

**Comment by DougBurke** [comment]
Yay.

**Comment by olaurino** [comment]
@wmclaugh this PR is a clear example of why our life would be simpler if we used py.test rather than unittest for defining test fixtures. Some tests in this PR have to rely on multiple inheritance with overlapping scopes, but all would be simpler with py.test fixtures.

@DougBurke we still can't rely on py.test as it has not been approved as a new OTS for CIAO, which is also why I am holding back publishing a PR with new tests for the datastack module.

**Comment by DougBurke** [comment]
Note that I am refactoring the offending test code (i.e. the use of multiple inheritance) as some of the logic should be pushed down to the model test code. I don't think that will remove the use of multiple inheritance, but let's see how it all shakes out.

For various reasons this PR will need major clean up before it's ready for review ;-)

**Comment by DougBurke** [comment]
So, @olaurino I think I would like to talk to you about how best to structure these tests, as I'd like to "do the same thing but for different modules", and maybe the approach I'm using here isn't appropriate. Or it could be a driver for new build requirements, as you mentioned above :-)

**Comment by olaurino** [comment]
@DougBurke are you waiting for an action on my part? I am not sure where we are with this.

**Comment by DougBurke** [comment]
I got "distracted" into trying to improve the test coverage and then fix up issues it showed. However, I've now forgotten exactly where I was with this.

At the moment, I view this PR as a "playground", spawning off a few PRs (as already done) and not anything that will be merged itself. I need to find some time to be able to get back up to speed with what I was doing.

**Comment by olaurino** [comment]
Is there a point in keeping this open as a PR, then? Or should it just go back to being a "simple" branch?

**Comment by DougBurke** [comment]
I've found it useful as a PR because of the travis testing ...

**Comment by olaurino** [comment]
I am ok with leaving it as a PR, but you would get the travis build if it were a branch as well. The build would be linked to each commit you push (if you push multiple commit, the build is triggered by the last commit).

**Comment by DougBurke** [comment]
I didn't realise you'd set up travis for every branch. I had assumed it was only for PRs and for the snapshot branch.

**Comment by DougBurke** [comment]
@olaurino - can you undelete this branch; there's still code in there that is relevant (see #143)?

**Comment by olaurino** [comment]
Done.

**Comment by DougBurke** [comment]
Ta - I couldn't immediately find the undelete branch option!

**Pull request closed without merging**
