### PR TITLE
update travis jobs with xspec 12.10.1

### PR DESCRIPTION
**Pull request by olaurino**

### CODE REVIEW

**Comment by DougBurke** [comment]
I assume you'll squash these once travis is green?

**Comment by olaurino** [comment]
Possibly.

What do you think of the errors in https://travis-ci.org/olaurino/sherpa/jobs/489262802?

**Comment by olaurino** [comment]
Wait, I guess that's expected. I guess we should "merge" this PR with #534.

**Comment by olaurino** [comment]
I rebased this on top of #534 to run the Travis jobs, but then we can just cherry-pick a single squashed commit in #534 and merge that one.

**Comment by DougBurke** [comment]
So, in XSPEC 12.10.0 - e.g. as provided in CIAO 4.11 - we have

```
% grep laor ~/local/ciao-4.11/ots/spectral/manager/model.dat 
laor           5  0.         1.e20           C_xslaor    add  0
laor2          7  0.         1.e20           C_laor2     add  0
```

and in XSPEC 12.10.1 we have

```
% grep laor ~/local/heasoft-6.25/spectral/manager/model.dat
laor           5  0.         1.e20           C_laor    add  0
laor2          7  0.         1.e20           C_laor2     add  0
```

and I assume they do not provide a `C_xslaor` version for "backwards" compatability. So I think this failure is expected here.

**Comment by DougBurke** [comment]
I've just rebased #534 so that it should match the current master state. It wasn't clear what you meant above, so apologies if I've messed something up here.

**Comment by olaurino** [comment]
No problem, I just didn't realize the new travis jobs wouldn't work without your changes in #534. So I rebased my stuff on top of #534 and pushed to trigger the travis jobs and make sure everything works. Then, assuming everything works, I'll close this PR and just cherry-pick a single commit in #534. Technically I still need to review that PR (I gave it a look), but I don't expect to any issues.

**Comment by DougBurke** [comment]
Note that #534 works around out favorite "bubble" test, by removing some tests of the covariance matrix completely, as I believe they are meaningless. We should probably review this test since it has caused some fun in a number of PRs recently.

**Comment by olaurino** [comment]
Yeah, I noticed that.

**Comment by olaurino** [comment]
closing in favor of #534.

**Pull request closed without merging**
