### PR TITLE
Pytest-doctestplus no longer supports python 3.5

### PR DESCRIPTION
**Pull request by Marie-Terrell**
This is the same issue seen previously for pytest-openfiles (PRs [#805](https://github.com/sherpa/sherpa/pull/805), [#806,](https://github.com/sherpa/sherpa/pull/806) and [#807](https://github.com/sherpa/sherpa/pull/807)). pytest-doctestplus no longer supports Python 3.5, but is still getting installed. 

At the moment, this is an issue with both of pytest-openfiles and pytest-doctestplus Conda packages not having Python>=3.6 and pytest>=4.6 (pytest-openfiles) or 4.0 (pytest-doctestplus) in their run requirements. When we install astropy into our Conda environment, pytest and these packages are also installed. This then manifests as the issue seen in the Travis Jobs when trying to load the Pytest modules.  If the run requirements are updated for these Conda packages, we should no longer need these workarounds. For now, I am implementing the same fix done for pytest-openfiles.

We could try to clean up the version requirements a bit by trying to install pytest with pip instead of Conda, but that may end up complicating things a bit.

### CODE REVIEW

**Comment by hamogu** [comment]
I opened an issue with pytest-doctestplus (https://github.com/astropy/pytest-doctestplus/issues/115). Not sure who takes care of the conda packaging, but maybe they can update their packaging scripts to avoid this problem for us in the future.

**Comment by Marie-Terrell** [comment]
Thank you. I also opened an issue [here](https://github.com/astropy/conda-channel-astropy/issues/181).

**Comment by bsipocz** [comment]
Do consider to switch to pip installs of these infrastructure packages for CI purposes. I'm afraid the conda packaging will always lag behind the pypi releases and it just adds extra chance to miss out on a release.

**Comment by Marie-Terrell** [comment]
Thank you @bsipoz. That is definitely something to consider for fixes in the future. We do need some packages from Conda, but we could look into still grabbing some of the deps from PyPI after creating the environment.

**Comment by bsipocz** [comment]
Yes, I only suggest doing it for infrastructure, pytest and related things. 

As for functional testing, there is benefits in staying with conda, especially if you rely on MLK, etc, and the primary workflow for users is to install sherpa from conda. (but then, these testing packages are not required to be installed by the users).

**Comment by Marie-Terrell** [comment]
As a brief update, the updated packages are now there for conda-forge and astropy. The old packages will still need to be removed (mentioned on the other Issue). I've also submitted an issue to Anaconda for updating the packages in defaults here: ContinuumIO/anaconda-issues#11864.

**Comment by Marie-Terrell** [comment]
Alright. A new issue popped up related to pytest. This time, it looks like it is not specifically a Conda package issue. Basically:

- This only fails for Python 3.5 for TEST=submodule. This is because pytest is installed through Conda (astropy will always pull it in) at a version that works in the environment. Then, pytest is updated when "pytest-cov" is pip installed. 
- This seems mainly due to combining the old and new pytest package. You can see a similar issue here.

So far, it looks like there are a few options for getting around this:

1. Change the "pip install pytest-cov" to a "conda install -yq pytest-cov" (a quick check shows that this all of the tests seem to pass here)
2. Use Conda to install Python and Xspec (if needed) and then use pip to install astropy or other Python packages. As mentioned above.
3. We could also try to add a version to the install for pytest-cov (either limiting pytest-cov as it now requires a newer version of pytest causing the issue or setting a pytest version). This is messy and not recommended, but technically still an option.

- Method 1:
    - pros: 
        - This would avoid us mixing the package managers (pip and conda) as much.
    - cons: 
        - We seem to be pushing ourselves further away from pip. We may want to consider how the setup should be testing to cover all use cases.
- Method 2:
    - pros: 
        - Actually seems to allow us to remove the pytest-openfiles and pytest-doctestplus requirements for the Travis Jobs.
    - cons: 
        - Would require a bit more testing
        - We would still need to consider the GitLab tests because they still rely on Conda (as they should).


For now, I have added a method 1 as a quick fix to get our tests working again. I recommend that we now consider implementing Method 2 in a separate PR for a "ful-fix" approach (reverting the method 1 change from here in the process). Though, with these changes, we may want to consider the Travis/GitLab test infrastructure as such:

- Travis:
    - Used to mainly test Sherpa against PyPi (pip) Python packages as this will allow us to always test against the latest version of packages (as much as possible). 
    - We would ONLY use Conda to install things that NEED to be installed with Conda (Python, Xspec, and Xspec deps). Then, we install any additional Python modules with pip (pytest, pytest-cov, astropy, or whatever else).
    - We could consider maintaining one Conda focused test here to still maintain an eye on future issues we may encounter in the Conda/GitLab testing before we get there.

- GitLab:
    - We would focus the testing in this section on the Conda users. This is already the case, so there would be no change here. However, we will need to more closely monitor build failures here because problems may arise as changes are merged and we might not realize (as they may be Conda specific and mainly PyPi packages are tested with Travis).

We should also consider how much we want/need to maintain Python 3.5 support (moving forward). If everything seems to be moving onto 3.6, this may become increasingly difficult on our end.

**Comment by hamogu** [comment]
Personally, I'm in favor of dropping Python 3.5 after 4.12.1 is out; in fact, we might want to drop 3.6, too. Python 3.9 is coming out before the next annual CIAO/Sherpa release (https://www.python.org/dev/peps/pep-0602/), so the next "big" release could support 3.7, 3.8, and 3.9. Three versions of Python is enough choice and enough work for us.

**Pull request merged**
