### PR TITLE
Errors in sherpa.opt pointed out by pyflakes

### PR DESCRIPTION
**Pull request by cdeil**
I had a look at `sherpa/optmethods/opt.py` today because I want to start working on #150 next week.

PyCharm pointed out a few errors when I opened up the file.
I think they are real and this is code that isn't covered by tests?
It's also possible to see those with e.g. pyflakes:
```
$ pyflakes-2.7 sherpa/optmethods/opt.py 
...
sherpa/optmethods/opt.py:82: undefined name 'InputError'
sherpa/optmethods/opt.py:224: undefined name 'nparx'
sherpa/optmethods/opt.py:243: undefined name 'result'
sherpa/optmethods/opt.py:244: undefined name 'result'
...
```

I think there's also real issues pyflakes can find in other files ... concretely I saw this:
```
$ pyflakes-2.7 sherpa/estmethods/ | grep 'undefined name'
sherpa/estmethods/__init__.py:316: undefined name '_est_funcs'
sherpa/estmethods/__init__.py:440: undefined name '_est_funcs'
```

@olaurino @DougBurke - How do you want to proceed here? Merge this PR as-is and then you continue fixing the issues pyflakes reports and adding regression tests? Or give me pointers how to fix these issues and what kinds of tests to add?

If you're considering adding a travis-ci build that runs static code analysis, in my experience [prospector](https://pypi.python.org/pypi/prospector) and `pyflakes` are easy and quite good, but `pyflakes` finds more issues and is better configurable on what to report / ignore.

### CODE REVIEW

**Comment by dtnguyen2** [comment]
opt.py is not used by sherpa, we are in the process of removing the file

**Comment by cdeil** [comment]
@dtnguyen2 - Ah, OK.

What about the error I mentioned in `sherpa/estmethods/__init__.py`?
```
$ pyflakes-2.7 sherpa/estmethods/ | grep 'undefined name'
sherpa/estmethods/__init__.py:316: undefined name '_est_funcs'
sherpa/estmethods/__init__.py:440: undefined name '_est_funcs'
```
https://github.com/sherpa/sherpa/blob/master/sherpa/estmethods/__init__.py#L316
https://github.com/sherpa/sherpa/blob/master/sherpa/estmethods/__init__.py#L440

This doesn't work, because the import is
```
import sherpa.estmethods._est_funcs
```
and not
```
from sherpa.estmethods import _est_funcs
```
right?

Is this also old code that will be removed, or should that be fixed?


PS: For Astropy and most affiliated packages we have the coverage report online, and generated for all pull requests:
https://github.com/astropy/astropy#project-status
https://coveralls.io/github/astropy/astropy
I find this very useful, it makes it quick to check which code is covered without having to produce a coverage report locally.
Add this for Sherpa?
(It's easy to set up via travis-ci, let me know if you want this and if I should make a pull request adding that to one of the builds.)

**Comment by DougBurke** [comment]
@cdeil - we are looking at doing something with the coverage reports, but haven't done so yet. Given that we have a bunch of "optional" packages, so the coverage result depends on the environment, I assume it's easy to say "only report the results from this particular build" (or some other manner)?

**Comment by cdeil** [comment]
@DougBurke - Right, what Astropy and most other packages do is to pick one build where all dependencies are available and generate the main coverage report for that one.

You can see how it's done technically here:
https://github.com/astropy/astropy/blob/master/.travis.yml#L106

The [coveralls](https://pypi.python.org/pypi/coveralls) command line tool is used to submit the report to the free https://coveralls.io/ service, which shows nice coverage reports that one can link to, e.g. to point out missing test coverage to contributors, or just to browse which parts of the code aren't covered yet.

**Comment by olaurino** [comment]
My experience with coveralls is that it does more harm than good. It may work better with Python than with Java, but with our Java projects I disabled it: even when robust tools like sonarqube (and common sense) detected coverage increase, coveralls for some reason signaled a decrease, staining perfectly fine PRs. I think it's good practice to run coverage analysis locally on small units during development, especially to check that one is testing what they think they are testing, so I never found coveralls particularly useful and I don't miss it. Plus, one can obtain 100% line coverage and have meaningless tests anyway. That being said, we may review the decision we made about coveralls in the future.

**Comment by cdeil** [comment]
@olaurino - I agree with your caveats / concerns concerning coverage and coveralls, but in the end I do think it's a bit useful to have. For Gammapy I set up coveralls, but I turned off the automatic commenting on pull requests, because I also found the "coverage has increased or decreased by 0.XX %" not helpful.
The way I use it is:
1. Sometimes check overall coverage and browse which code isn't covered. Having it online can be useful to point out some non-tested function or method to other contributors and ask them to add a test for this (that's usually a good "getting started" or "good first pull request")
2. Sometimes for PRs that add a lot of new code, link to the coverage report and point out the main chunks of new code that aren't covered.

PS: locally for Sherpa I get a coverage of 45% :
https://gist.github.com/cdeil/062380f016b7ebdc8e59#file-gistfile1-txt-L417

Is it normal / useful that the coverage report includes `test_*` files?
Am I running the tests correctly or am I doing something wrong?
Having a "reference" coverage report for master online for Sherpa where all dependencies are present and the tests are run correctly would be useful IMO.

**Comment by olaurino** [comment]
> Is it normal / useful that the coverage report includes test_* files?

They say it's normal (it's the default behavior), but I have to say at first I was surprised too. The reasoning seems to be that you may want to know if some of your tests are not running, or in any case you don't have full coverage of your tests.

I have locally a `pytest-cov` file that disables that, with the following content:

````
[run]
omit = *test_*
branch = True
````

> Am I running the tests correctly or am I doing something wrong?

I don't think you are doing anything wrong. We know that the coverage of tests accompanying code is not enough, but reasons for that go back in time and there is no simple/rapid fix. We are trying to add new coverage whenever possible, even if it's not in the specific scope of a PR (e.g. we added tests for several stats, not just for `wstat`, when we included `wstat`, and I am adding plenty of tests in the scope of the otherwise simple #22 fix). There are tests that run in CIAO, but that do not accompany the code. Some of them were "ported" several years go, some were not. The full code coverage (line and branch combined) is of about 60% when all the dependencies are present, including ds9 and xspec.

I am planning to add plenty of unit tests in the scope of the python3 migration.

> Having a "reference" coverage report for master online for Sherpa where all dependencies are present and the tests are run correctly would be useful IMO.

The decision was made before we published the code to GitHub (we used to have the configuration commented out in the travis config), but we can discuss that again. In any case thanks for your input!

**Comment by olaurino** [comment]
I went back to this PR, and I noticed that we got somehow carried away of the main topic.

Given that `opt.py` is going away, it remains the problem of `_est_funcs`. Maybe I am forgetting something basic about Python that I should know (and tracking PEPs about imports is hard indeed), but the code actually works, despite the fact that I thought it shouldn't. And it is indeed covered by our tests.

Once 'sherpa.estmethods._est_funcs` is imported, `_est_funcs` appears in the globals of `estmethods.__init__.py`. I wonder if this works by accident because of the implementation or because it is somehow part of the spec.

**Comment by DougBurke** [comment]
Also, do we have a PR yet for the removal of `opt.py`?

**Comment by olaurino** [comment]
@cdeil I am going to create a new PR getting rid of `opt.py` and keeping your change for `_est_funcs`: for this latter change, even if it is working and we have coverage I guess it's safer to get your change.

**Comment by olaurino** [comment]
Replaced by #192.

**Pull request closed without merging**
