### PR TITLE
Clean up ciao files

### PR DESCRIPTION
**Pull request by olaurino**
# Description
This PR removes ciao-related files and some ciao-related code that was also obsolete.

The files removed by this PR will be moved to a different location, either in the CIAO source code repository or in a different git repository, and appropriately edited according to the new CIAO setup.

### CODE REVIEW

**Comment by DougBurke** [comment]
Looks good to me.

Should this be against master or the release/4.8.0 branch?

**Comment by olaurino** [comment]
master. This is intended as part of a post-ciao-release clean-up.

**Comment by DougBurke** [comment]
Do we need a milestone for this work (i.e. is there more planned), or can it just be 4.8?

**Comment by olaurino** [comment]
@DougBurke sorry for not replying earlier. Milestones are important so that we track the issues we decide to address, as it helps tracking progress. We may add milestones to PRs in some cases, but I don't think that's too important, given the experience with the past development cycle.

So no, I don't think we need a milestone for this.

**Comment by olaurino** [comment]
Rebasing, original tip was cd2a754

**Pull request merged**
