### PR TITLE
datastack module documentation update

### PR DESCRIPTION
**Pull request by DougBurke**
# Release Notes

Update the `sherpa.astro.datastack` module documentation to include information from the
CIAO ahelp documentation and to match the style used by the `sherpa.astro.ui` module.

# Details

There are no code changes here, only documentation updates (and moving the
copyright statement to the start of the file). The documentation changes
include a major expansion of the module-level docstring, addition of
various functions, and updating to numpy-style formatting. The new text
is based on the CIAO ahelp documentation for the datastack module.

### CODE REVIEW

**Comment by anetasie** [comment]
We need to give credit to Tom Aldcroft, as the code is basically taken  as was  written and designed in his datastack module.

**Comment by DougBurke** [comment]
I actually looked at this, and found this numpy guideline suggesting that
authors shouldn't be in docstrings

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#documenting-modules

We have a similar issue with the pyblocxs code in #111 which I haven't
really addressed either

**Comment by olaurino** [comment]
I am OK with merging this PR, as long as we have a plan for giving credit to the author of the original source code, since the PR removed this information.

**Comment by DougBurke** [comment]
I have added an acknowledgments section. Longer term we need a better solution (e.g. once the planned on-line documentation is available), at which point this can be re-worked.

**Pull request merged**
