### PR TITLE
Bug #46 astropy handle commentary cards

### LINKED ISSUE #46: BUG: sherpa.astro.ui.pack_pha/save_data fail with PyFITS backend for CIAO PHA files
## Summary

The `ui.unpack_pha` and `ui.save_data` functions fail when:

a) the PyFITS backend is in use
b) the PHA file uses the LONGSTRN OGIP convention, as CIAO does

The error raised is `ValueError: Illegal value: ...`.

***EDIT***: it's not the `LONGSTRN` keyword that is the problem, it is the presence of "commentary" cards (i.e. key=HISTORY, COMMENT, or blank) which causes the problem. Chandra files have both COMMENT and HISTORY cards, and the failure reported above is due to the COMMENT cards that follow the `LONGSTRN` keyword in the header.

There are deprecation warnings, but these are mentioned in #27 so are not considered here.

## Details

I have installed pyfits using conda (using the conda.binstar.org/sherpa channel), so that I have

```
% conda list pyfits
# packages in environment at /export/local/anaconda/envs/sherpa-master:
#
pyfits                    3.3.0                np18py27_1
```

With the latest master branch of Sherpa, I get, when run from its top-level directory:

```
% ipython
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sherpa

In [2]: sherpa.__version__
Out[2]: '4.7+427.g57e2d92'

In [3]: from sherpa.astro import ui
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [4]: ui.load_pha('sherpa/astro/datastack/tests/data/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa/astro/datastack/tests/data/3c273.pi'
statistical errors were found in file 'sherpa/astro/datastack/tests/data/3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file sherpa/astro/datastack/tests/data/3c273.arf
read RMF file sherpa/astro/datastack/tests/data/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa/astro/datastack/tests/data/3c273_bg.pi'
statistical errors were found in file 'sherpa/astro/datastack/tests/data/3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file sherpa/astro/datastack/tests/data/3c273_bg.pi
```

So far, so good. If I call `unpack_pha` on this dataset, I get PyFITS deprecation warnings (see #27), but also an error (note that you get essentially the same warnings and error if you call

    ui.save_data('/tmp/src.fits', ascii=False, clobber=True)

here, which isn't too surprising because I think `save_data` is implemented in terms of `pack_pha`):

```
In [5]: out = ui.pack_pha(1)
/export/local/anaconda/envs/sherpa-master/lib/python2.7/site-packages/pyfits/card.py:70: PyfitsDeprecationWarning: The CardList class has been deprecated; all its former functionality has been subsumed by the Header class, so CardList objects should not be directly created.  See the PyFITS 3.1.0 CHANGELOG for more details.
  PyfitsDeprecationWarning)
sherpa/astro/io/pyfits_backend.py:896: PyfitsDeprecationWarning: The append function is deprecated as of version 3.1 and may be removed in a future version.

        Use :meth:`Header.append` instead.
  hdrlist.append(pyfits.Card( str(key.upper()), header[key] ))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-bb035208f5de> in <module>()
----> 1 out = ui.pack_pha(1)

<string> in pack_pha(id)

/export/sherpa/sherpa-master/sherpa/astro/ui/utils.pyc in pack_pha(self, id)
   4716
   4717         """
-> 4718         return sherpa.astro.io.pack_pha(self._get_pha_data(id))
   4719
   4720     ### DOC-TODO: labelling as AstroPy HDUList; i.e. assuming conversion

/export/sherpa/sherpa-master/sherpa/astro/io/__init__.pyc in pack_pha(dataset)
    410 def pack_pha(dataset):
    411     data, col_names, hdr = _pack_pha( dataset )
--> 412     return backend.set_pha_data('', data, col_names, hdr, packup=True)

/export/sherpa/sherpa-master/sherpa/astro/io/pyfits_backend.pyc in set_pha_data(filename, data, col_names, header, ascii, clobber, packup)
    894         if header[key] is None:
    895             continue
--> 896         hdrlist.append(pyfits.Card( str(key.upper()), header[key] ))
    897
    898     collist = []

/export/local/anaconda/envs/sherpa-master/lib/python2.7/site-packages/pyfits/card.pyc in __init__(self, keyword, value, comment, **kwargs)
    445                 self.keyword = keyword
    446             if value is not None:
--> 447                 self.value = value
    448
    449         if comment is not None:

/export/local/anaconda/envs/sherpa-master/lib/python2.7/site-packages/pyfits/card.pyc in value(self, value)
    567                                  (float, complex, bool, Undefined, np.floating,
    568                                   np.integer, np.complexfloating, np.bool_)):
--> 569             raise ValueError('Illegal value: %r.' % value)
    570
    571         if isinstance(value, float) and (np.isnan(value) or np.isinf(value)):

ValueError: Illegal value:   This FITS file may contain long string keyword values that are
  continued over multiple keywords.  The HEASARC convention uses the &
  character at the end of each substring which is then continued
  on the next keyword which has the name CONTINUE..

```

It looks like PyFITS either doesn't support, or we need to "turn on the necessary flags/switches/..." to do so, the LONGSTRN OGIP convention that CIAO uses in its headers:

```
% dmlist sherpa/astro/datastack/tests/data/3c273.pi header,clean,raw
...
LONGSTRN     = OGIP 1.0             / The HEASARC Long String Convention may be used.
COMMENT      =   This FITS file may contain long string keyword values that are /
COMMENT      =   continued over multiple keywords.  The HEASARC convention uses the & /
COMMENT      =   character at the end of each substring which is then continued /
COMMENT      =   on the next keyword which has the name CONTINUE. /
...
``` 

Given that the PyFITS code read this in (see below), suggests that there may be support for it (or there's some issue with how COMMENT keys are being processed):

```
In [1]: from sherpa.astro import ui
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: ui.load_pha('sherpa/astro/datastack/tests/data/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa/astro/datastack/tests/data/3c273.pi'
statistical errors were found in file 'sherpa/astro/datastack/tests/data/3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file sherpa/astro/datastack/tests/data/3c273.arf
read RMF file sherpa/astro/datastack/tests/data/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa/astro/datastack/tests/data/3c273_bg.pi'
statistical errors were found in file 'sherpa/astro/datastack/tests/data/3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file sherpa/astro/datastack/tests/data/3c273_bg.pi

In [3]: d = ui.get_data()

In [4]: d.header
d.header

In [4]: d.header['LONGSTRN']
Out[4]: 'OGIP 1.0'

In [5]: d.header['COMMENT']
Out[5]:
  This FITS file may contain long string keyword values that are
  continued over multiple keywords.  The HEASARC convention uses the &
  character at the end of each substring which is then continued
  on the next keyword which has the name CONTINUE.

In [6]:
```

### PR DESCRIPTION
**Pull request by DougBurke**
This replaces #91 - the commit history is a lot cleaner and does not conflict with the `master` branch.

Resolve #46 

# Release Notes

Fix for writing out FITS files using the save_pha and save_table commands - and the associated pack_pha and pack_table commands - when using the astropy I/O back end (issue #46). It does not affect CIAO users (i.e. users of the crates back end).

Fix for when the `notice2d_id`, `notice2d_image`, and the `ignore` version functions are called with an invalid identifier (i.e. an identifier that i snot an integer or string value). The error is now an `ArgumentTypeErr` with the message "'ids' must be an identifier or list of identifiers". It was a `NameError` with the message "global name '_argument_type_error' is not defined".

Improves the `sherpa/astro/ui/tests/test_astro_ui.py` test suite.

# Notes

The primary fix is to handle the so-called commentary cards (i.e. those with a keyword of HISTORY, COMMENT, or blank) properly, when converting from the Sherpa data structure (the header field in the DataXXX object) to an astropy FITS header. This is a general-purpose change (so both FITS tables, images) but testing has focussed on the PHA case, as that was where the issue was first seen. More tests are needed for sherpa.astro.ui, but that's outside the scope of this PR.

The NameError fix was just that the _argument_type_error routine has not been imported from the necessary module.

The code has seen PEP-8 fixes and minor refactorings.

The tests are not added to `sherpa/astro/io/tests/test_astro_io.py` since there are issues with

### CODE REVIEW

**Comment by DougBurke** [comment]
Note that the test failure here was to test that there was a problem with the Travis-CI test suite and pytest-2.8.0. It has been fixed in #108.

**Comment by DougBurke** [comment]
Merging in #108 has fixed the test failures.

**Comment by olaurino** [comment]
Rebasing to resolve conflicts (derived from reverting #89, on which this PR was based). Original tip was at caa5c10

**Comment by DougBurke** [comment]
@olaurino - this looks good to me.

**Pull request merged**
