### PR TITLE
Fixes and PEP 8/pyflakes updates for utils

### PR DESCRIPTION
**Pull request by DougBurke**
These commits fix a potential error, in that `OutOfBoundErr` exceptions were not being caught (although it's not actually clear that this is ever thrown). There were several places where screen output used either `print` or `sys.stderr.write`: these have been changed to use the `debug` and `warning` loggers instead (respectively). Several routines which use `min` and `max` as variable names have been changed. There are very-minor documentation changes for Sphinx (mainly change `:` to `::` when introducing some maths).

It also addresses a number of pyflakes/PEP-8 violations: more Pythonic use of boolean variables (e.g. `not xxx` rather than `False == xxx`); add spaces between operators; remove spaces before/after various brackets; line length; two blank lines between top-level declarations; explicit module export; remove blank characters at the ends of lines.

The commits have been broken up into separate sections to try and make reviewing the changes somewhat easier.

The reason for these changes is that I want to make some changes to the test class code, but found a number of issues that were being flagged up by

```
pyflakes "$1"
pep8 --ignore=E221,E701,E202 --repeat "$1"
```

so decided to clean these up first.

### CODE REVIEW

**Comment by DougBurke** [comment]
Note that these changes are included in #71 - perhaps due to my lack of git mumbo jumbo.

**Comment by olaurino** [comment]
@DougBurke Thanks for noting it. In general, we should avoid dependencies between PRs, but sometimes that's just the way to go, as long as we know that one PR has to be merged before the other.

In this case, I wonder if we shouldn't close #70 and work with #71 as a single clean-up PR. Otherwise I would suggest we rebase #71 on top of master and keep them separate, since they do not overlap.

**Comment by DougBurke** [comment]
I think that some form of rebasing is going to be needed once #59 is
merged. One reason for keeping them separate is that it might be a bit
cleaner to review the changes broken up this way (i.e. two PRs), but I
don't have a strong opinion on this.

**Comment by olaurino** [comment]
This PR has been replaced by #78.

**Pull request closed without merging**
