### PR TITLE
WIP: Work around failure cases when backscal is an array

### PR DESCRIPTION
**Pull request by DougBurke**
Work on addressing issues seen when a PHA file (e.g. grating dataset) has an array `BACKSCAL` value. This needs more work (e.g. tests being added) and the consequences worked out before it can be merged.

# Details

For grating PHA data sets the background scale value can vary with bin,
and so is returned as an array. This causes the creation of the
BackgroundSumModel instance - which is created whenever a model instance
is being created by sherpa.astro.ui functions like get_model and show_all -
to fail with a TypeError, as '%g' % backscale errors out.

This change traps this error and replaces the actual scaling value by
a token ("bkgscale"), which lets the process proceed. It is unclear
however what the semantics of the string representation of a model is:
is it purely for display purposes, in which this replacement is
okay, or is it meant to be actionable/machine readable (e.g. when
saved via the ui.save_all function)?

### CODE REVIEW

**Comment by DougBurke** [comment]
I think the XSPEC tests are failing because XSPEC. I'm not sure why XSPEC, but I'm blaming XSPEC. At least XSPEC 12.9.0.

**Comment by DougBurke** [comment]
Going to rebase to pick up the recent Travis fixes for XSPEC. Tip was @50e6db1

**Comment by DougBurke** [comment]
yay. it was the xspec/travis issue that caused the previous test run to fail.

**Comment by DougBurke** [comment]
You can try this approach without installing this PR by monkey patching the constructor for the background model class, before doing anything. Please be aware that I haven't evaluated the downstream consequences of this, so take care and **please** report back if you have success or failure.

As an example:

a) old failing code

```
from sherpa.astro import ui

ui.load_data("problem-file.pha")
ui.set_source(1, ui.xsphabs.abs1 * ui.xspowerlaw.pl1)
ui.set_bkg_model(1, ui.xspowerlaw.bkpl1)
print("\n*** stat = {}".format(ui.calc_stat()))
print("\n*** source: {}".format(ui.get_source()))
print("\n*** model: {}".format(ui.get_model()))
```

b) new hopefully not-failing code

```
from sherpa.astro import ui

from sherpa.models.model import CompositeModel, ArithmeticModel
from sherpa.astro.background import BackgroundSumModel

# Code taken from https://github.com/sherpa/sherpa/pull/435 but comments have been removed
# (and not necessarily kept up to date with any changes to this PR).
#
def newinit(self, srcdata, bkgmodels):
    self.srcdata = srcdata
    self.bkgmodels = bkgmodels
    scale_factor = self.srcdata.sum_background_data(lambda key, bkg: 1)
    bkgnames = [model.name for model in bkgmodels.values()]
    bkgstr = ' + '.join(bkgnames)

    # this is the hack to support vector backscal values
    try:
        name = '%g * (' % scale_factor + bkgstr + ')'
    except TypeError:
        name = 'bkgscale * ({})'.format(bkgstr)

    CompositeModel.__init__(self, name, self.bkgmodels.values())


BackgroundSumModel.__init__ = newinit

### rest of the code is as before
ui.load_data("problem-file.pha")
ui.set_source(1, ui.xsphabs.abs1 * ui.xspowerlaw.pl1)
ui.set_bkg_model(1, ui.xspowerlaw.bkpl1)
print("\n*** stat = {}".format(ui.calc_stat()))
print("\n*** source: {}".format(ui.get_source()))
print("\n*** model: {}".format(ui.get_model()))
```

**Comment by DougBurke** [comment]
Hmmm, if I try fitting a model to the background and then ignore some data, I see an error in the fit, such as in this large backtrace (with CIAO 4.9 and the hack above applied):

```
sherpa-44> fit()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-749b6e6de45a> in <module>()
----> 1 fit()

<string> in fit(id, *otherids, **kwargs)

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/ui/utils.py in fit(self, id, *otherids, **kwargs)
   9301         """
   9302         kwargs['bkg_only'] = False
-> 9303         self._fit(id, *otherids, **kwargs)
   9304 
   9305     def fit_bkg(self, id=None, *otherids, **kwargs):

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/ui/utils.py in _fit(self, id, *otherids, **kwargs)
   9405                     i).mask & numpy.isfinite(self.get_data(i).get_x())
   9406 
-> 9407         res = f.fit(**kwargs)
   9408         res.datasets = ids
   9409         self._fit_results = res

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/fit.py in run(fit, *args, **kwargs)
     49     def run(fit, *args, **kwargs):
     50         fit.model.startup()
---> 51         result = func(fit, *args, **kwargs)
     52         fit.model.teardown()
     53         return result

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/fit.py in fit(self, outfile, clobber)
   1079             raise FitErr('binhas0')
   1080 
-> 1081         init_stat = self.calc_stat()
   1082         # output = self.method.fit ...
   1083         output = self._iterfit.fit(self._iterfit._get_callback(outfile, clobber),

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/fit.py in calc_stat(self)
    994         """
    995 
--> 996         return self._calc_stat()[0]
    997 
    998     def calc_chisqr(self):

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/fit.py in _calc_stat(self)
    975         # TODO: is there anything missing here that
    976         #       self._iterfit.get_extra_args calculates?
--> 977         return self.stat.calc_stat(self.data, self.model)
    978 
    979     def calc_stat(self):

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/stats/__init__.py in calc_stat(self, data, model)
    498         data, model = self._validate_inputs(data, model)
    499         fitdata = data.to_fit(staterrfunc=self.calc_staterror)
--> 500         modeldata = data.eval_model_to_fit(model)
    501 
    502         return self._calc(fitdata[0], modeldata,

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/data.py in eval_model_to_fit(self, modelfuncs)
    505 
    506         for func, data in izip(modelfuncs, self.datasets):
--> 507             total_model.append(data.eval_model_to_fit(func))
    508 
    509         return numpy.concatenate(total_model)

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/data.py in eval_model_to_fit(self, modelfunc)
   1192 
   1193     def eval_model_to_fit(self, modelfunc):
-> 1194         return self.apply_filter(modelfunc(*self.get_indep(filter=True)))
   1195 
   1196     def sum_background_data(self,

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/models/model.py in __call__(self, *args, **kwargs)
    168         if (len(args) == 0 and len(kwargs) == 0):
    169             return self
--> 170         return self.calc([p.val for p in self.pars], *args, **kwargs)
    171 
    172     def _get_thawed_pars(self):

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/instrument.py in calc(self, p, x, xhi, *args, **kwargs)
    484         # x could be channels or x, xhi could be energy|wave
    485 
--> 486         src = self.model.calc(p, self.xlo, self.xhi)
    487         src = self.arf.apply_arf(src, *self.arfargs)
    488         return self.rmf.apply_rmf(src, *self.rmfargs)

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/models/model.py in calc(self, p, *args, **kwargs)
    504         nlhs = len(self.lhs.pars)
    505         lhs = self.lhs.calc(p[:nlhs], *args, **kwargs)
--> 506         rhs = self.rhs.calc(p[nlhs:], *args, **kwargs)
    507         try:
    508             val = self.op(lhs, rhs)

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/models/model.py in calc(self, p, *args, **kwargs)
    504         nlhs = len(self.lhs.pars)
    505         lhs = self.lhs.calc(p[:nlhs], *args, **kwargs)
--> 506         rhs = self.rhs.calc(p[nlhs:], *args, **kwargs)
    507         try:
    508             val = self.op(lhs, rhs)

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/background.py in calc(self, p, *args, **kwargs)
     44             return bmodel(*args, **kwargs)
     45 
---> 46         return self.srcdata.sum_background_data(eval_bkg_model)            

/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/data.py in sum_background_data(self, get_bdata_func)
   1206             if backscal is not None:
   1207                 backscal = self._check_scale(backscal, group=False)
-> 1208                 bdata = bdata / backscal
   1209 
   1210             areascal = bkg.areascal

ValueError: operands could not be broadcast together with shapes (16349,) (16384,) 
sherpa-45> 
```

**Comment by DougBurke** [comment]
About to rebase. Tip was 95bee9c

**Comment by DougBurke** [comment]
So, I believe the problem with the suggested fix is that the backscale array is set at the time the model is created, but it needs to reflect the current filtering and grouping applied to the data (so it depends on the evaluation context).

This suggests a more-significant change is needed.

**Comment by hamogu** [comment]
I think the backscal array needs to be part of the dataspace definition in the same way that systematic and statistical uncertainty are. In that scheme, backscal would be a property with a getter function that takes into account grouping and filter at the time of retrieval like `get_dep()` or `get_error()` already do (of course, the function is simple when backscal is a number, not an array).

That's a fairly invasive change, but conceptually I don't see a way around it.

**Comment by DougBurke** [comment]
Note that this is a "different" backscal to the value get_backscal  calculates (for reasons). Technically get_backscal already supports filtering and grouping.

**Comment by DougBurke** [comment]
I am closing this as I hope #869 will address this, but I can guarantee that this PR isn't going to work.

**Pull request closed without merging**
