### PR TITLE
Improve documentation on ASCII file support and minor bug fix

### PR DESCRIPTION
**Pull request by DougBurke**
Release Notes
-------------

Improve the documentation for file I/O in `sherpa.ui`, including

* be explicit about ASCII support only (including remove mention of FITS support)
* add documentation for the support routines (e.g. those in `sherpa/io.py`) that actually do the I/O

Improve documentation for `load_table_model`, in particular the file support.

Fix unknown error classes in `sherpa.ui.utils`: these are in "hard to exercise" code paths (since there have been no reports about the unknown symbols).

There have been PEP8-related code changes.

Notes
-----

Ideally the fix for the unknown error classes would be in a separate PR but I don't have the time to rework this.

### CODE REVIEW

**Comment by olaurino** [comment]
It looks good to me. I'd say merge it.

However, should we make it a task (maybe even part of the python 3 migration) that we unify `sherpa.astro.ui` and `sherpa.ui` to reduce a lot of code duplication and functionality overlap?

**Comment by DougBurke** [comment]
@olaurino - there's a lot of places we could look at for review (e.g. I'm looking at `sherpa.astro.io` and `sherpa.io` in #162)! The `ui` modules do have a lot of overloaded code with subtly (and not-so-subtly) different semantics, and I think they are too large (they've been a pain when I was looking at sphinx). Perhaps it's worth noting things like this down on the wiki, rather than in issues (I did start with a page on model evaluation which I need to get back to finishing off), so they don't get lost and can perhaps provide more of an overview of what we'd like to do?

**Comment by olaurino** [comment]
Let's make it an item for the next meeting, then. I can see pros and cons of using the wiki and tracking issues. Consolidation of `sherpa.astro.[ui|io|??]` and `sherpa.[ui|io|??]` would be a big task anyway.

**Comment by olaurino** [comment]
And it goes without saying, any time we spend fixing these issues is time not spent implementing science features. Which is why making it part of the python 3 migration might be a good idea: a smaller code base can be ported more easily than a larger code base.

**Pull request merged**
