### PR TITLE
updating Sherpa citations

### PR DESCRIPTION
**Pull request by anetasie**
I added the citation to the most recent paper accepted and posted to astro-ph. I included the citation to astro-ph and plan to update when we have the paper published in ApJ Supp.

`sherpa.citation('latest')` now includes the following, after the Zenodo reference:

```
The most recent article to appear in the Astrophysical Journal Supplement Series:

@ARTICLE{2024arXiv240910400S,
       author = {{Siemiginowska}, Aneta and {Burke}, Douglas and {G{"u}nther}, Hans Moritz and {Lee}, Nicholas P. and {McLaughlin}, Warren and {Principe}, David A. and {Cheer}, Harlan and {Fruscione}, Antonella and {Laurino}, Omar and {McDowell}, Jonathan and {Terrell}, Marie},
        title = "{Sherpa: An Open Source Python Fitting Package}",
      journal = {arXiv e-prints},
     keywords = {Astrophysics - Instrumentation and Methods for Astrophysics, Astrophysics - High Energy Astrophysical Phenomena},
         year = 2024,
        month = sep,
          eid = {arXiv:2409.10400},
        pages = {arXiv:2409.10400},
          doi = {10.48550/arXiv.2409.10400},
archivePrefix = {arXiv},
       eprint = {2409.10400},
 primaryClass = {astro-ph.IM},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2024arXiv240910400S},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

```

### CODE REVIEW

**Comment by DougBurke** [comment]
@anetasie - unfortunately I have tests that explicitly check the citation output (so I can check it's doing the right thing), and this now fails because of your changes. So the tests will need updating.

**Comment by anetasie** [comment]
@DougBurke which test needs to be updated?

**Comment by DougBurke** [comment]
You would have to run the tests yourself to find out. Or review the output from the CI runs.

**Comment by anetasie** [comment]
@DougBurke The failed test is `test_sherpa.py` with the hardcoded citations, but I'm not sure how to fix it. Here is the failure:

``` 
___________________________ test_citation_hardcoded ____________________________

tmp_path = PosixPath('/tmp/pytest-of-runner/pytest-0/test_citation_hardcoded0')

    def test_citation_hardcoded(tmp_path):
        """Check citation works for hardcoded queries."""
    
        citefile = tmp_path / 'cite.txt'
        with citefile.open(mode='w') as fh:
            sherpa.citation('4.8.0', filename=fh, clobber=True)
    
        cts = citefile.read_text('ascii').split('\n')
        assert cts[0].startswith('You are using Sherpa ')
        assert cts[1] == ''
        assert cts[2] == 'Sherpa 4.8.0 was released on January 27, 2016.'
        assert cts[3] == ''
        assert cts[4] == '@software{sherpa_2016_45243,'
>       assert len(cts) == 65
E       AssertionError: assert 86 == 65
E        +  where 86 = len(['You are using Sherpa 0+untagged.1.g3b58f84 (it is not a released version).', '', 'Sherpa 4.8.0 was released on January 27, 2016.', '', '@software{sherpa_2016_45243,', '  author       = {Doug Burke and', ...])
```

**Comment by DougBurke** [comment]
So, the test is checking that you have the correct number of lines in the output, so if you try the citation command - e.g.

```
>>> from sherpa import citation
>>> citation('4.8.0')
```

and it looks okay then change the test so it checks that the len is 86.

I don't know if there are other checks that the test makes which might need similar changes, but I don't ahve time to help out much more deeply

**Comment by anetasie** [comment]
@DougBurke the test is fixed.

**Review by DougBurke — APPROVED** [review]

**Pull request merged**
