### PR TITLE
Travis to GitHub actions

### PR DESCRIPTION
**Pull request by Marie-Terrell**
This PR removes the Travis testing and adds in two GitHub Actions Workflows.

- The Conda workflow: Closely resembles our current Travis testing. Minor modifications to update Xspec and reflect any difference between Travis and GitHub Actions.
- The Pip workflow: Adds a few tests that do not require Conda (no Xspec) and focuses on testing a pip packages. There are occasionally times when new versions become available through Conda and Pip at different times or with different version requirements. This serves to bridge that gap. There are currently no macOS tests currently in the pip workflow.

It will be noted that there is a slight difference in the way the versions/packages for dependencies are listed for each workflow. This was done for a couple of reasons:

- There is a slight difference in the way pip and Conda define versions for installations (ranges, wildcards, etc.)
- Sometimes we want to define the package to be install (just grabbing the latest version). Sometimes we want to only grab specific versions (unsupported, issues, testing purposes, etc.)

If there are any issues and/or recommendations, please let me know.

### CODE REVIEW

**Comment by DougBurke** [comment]
@Marie-Terrell - is something odd in our sherpa repository since we don't seem to be seeing any actions being triggered by this PR (it was one of the things that made me stop working on #1007)?

**Comment by Marie-Terrell** [comment]
I don't believe so. The sherpa/sherpa repo settings should allow this to run. Though, this worked in my repository (as a branch and not a PR). So, I am currently trying to see if it is this line "on:  [push, pull_request]". Or something more?

**Comment by DougBurke** [comment]
Best of luck ...

**Comment by DougBurke** [comment]
@Marie-Terrell I wonder if this is the issue

> If you also want to run actions on PRs from forked repositories, you need further config because pushes to forks do not count as pushes to your repo.

which I found in https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/9

I've been looking at the GitHub Actions documentation and (I may have missed it) it doesn't seem to make this clear. [I've just been looking at the astropy workflows at https://github.com/astropy/astropy/tree/master/.github/workflows and it's not clear they have to do anything because of PRs from forked repositiories, but they have a miore-complex setup than we do]

**Comment by Marie-Terrell** [comment]
I am not entirely sure either. That thread seems to be focused more on not triggering twice. I have tried messing with the Sherpa organization permissions related to this (all reverted because it did not work). I do note [this comment](https://github.community/t/github-actions-are-not-shown-in-the-draft-pr-from-a-fork/17871/3):

> According to the discusstion with the engineering team, this behavior is currently by design.
A fork can not introduce workflows for the first time and cause the GitHub Actions app to be installed. This prevents a malicious use from forking public repos that are not using actions and getting them to run workflows.

It is entirely possible that this has changed (as there has been quite some time between that comment and now), but that might be the issue. Though, if that is the issue, I would then question how that impacts us for future workflow updates (as opposed to new workflows or adding a workflow for the first time). Honestly, it is really not quite clear. I have also been utilizing the Astropy workflows for a lot of the design and do not see what we could be missing (if it is in the files and not in settings, permissions, etc.).

**Comment by DougBurke** [comment]
@Marie-Terrell and I have been discussing this and we believe it makes sense to merge this so we have it on the master branch and hopefully it'll all start working. If not we can look at resurrecting the Travis tests removed in this PR.

**Review by DougBurke — APPROVED** [review]
I haven't looked through the details, but it'll be pretty obvious if it isn't working!

**Comment by hamogu** [comment]
👍 
I'm working on converting one of my other packages that needs conda to GH actions so and I admit I'm waiting this to work out so that I can use this as a template for my package ;-)

**Comment by DougBurke** [comment]
@Marie-Terrell - I don't know if you had done anything, but I have just pushed a copy of your PR to the main sherpa repository (branch = marie-travis-to-github-actions) and was starting a PR, but then I noticed the GitHub actions started on this PR.

I'm going to take this as a win, however it happened.....

 ¯\_(ツ)_/¯

**Comment by Marie-Terrell** [comment]
I haven't done anything recently that should have changed things. Based on the shortened SHA attached to the rest run it looks like the branch you created did trigger the tests. Nice! 
Now, hopefully, future tests runs will not need anything special. Maybe future updates to the workflow (depending on the exact reasoning), but we can always finagle it this way if that is the case.

**Comment by DougBurke** [comment]
I am not too concerned about the reduction in the lines tested. It could just be a case that we don't have exactly equal runs between the old and new systems, and I believe we have ample evidence that "something is strange™" with the coverage checks anyway.

**Comment by Marie-Terrell** [comment]
Agreed. I am comfortable enough with this going in whenever. Someone can then test rebase a simple PR if they wish to then check if the tests run properly. That should then give us a good idea if this is actually working now

**Pull request merged**
